// Copyright (C) 2014 Open Rice & Panasonic Corporation. All Rights Reserved.
//
//****************************/
// File Name: global.js
// Purpose: This document creates common components for all screens.
// File Created Date: 17-Oct-2013
// Release Date: 02-Jan-2014
// Release Version: 1.4
//****************************/
try{(function(win){var global={"screen":0,"gadget":-1};hotKeyObj={"hotKeyCur":1};global.keyCodeDic={};global.focusedDom={};global.loadOn=false;global.disableSearch=false;global.keyCodeDic[38]="arrowup";global.keyCodeDic[40]="arrowdown";global.keyCodeDic[37]="arrowleft";global.keyCodeDic[39]="arrowright";global.keyCodeDic[13]="ok";global.keyCodeDic[8]="return";global.keyCodeDic[403]="red";global.keyCodeDic[404]="green";global.keyCodeDic[405]="yellow";global.keyCodeDic[406]="blue";global.urlParams;global.rigthNav=null;global.cookieSet=false;global.defaultSet=false;global.MY_HSData={'countryCode':'MY','countryName':'Malaysia','cityName':'Klang Valley','cityId':'500'};global.location=document.getElementById("currentLocationTxt");global.innerParent=document.getElementById("innerSection");global.serverList={};global.OR_Token="http://panasonic.openrice.com";global.serverList={"India":"http://ptv.api.in.openrice.com","Indonesia":"http://ptv.api.id.openrice.com","Malaysia":"http://ptv.api.my.openrice.com","Philippines":"http://ptv.api.ph.openrice.com","Singapore":"http://ptv.api.sg.openrice.com"};global.bufferImages=function(){var imagesCode="";var imagesBufArray=["images/exit_curser.png","images/menuCursor.png","images/normal_selectedMenu.png","images/error_icon.png","images/popup_box.png","images/star.png","images/bg_box.png","images/bottom_banner.png","images/gridTheme.png","images/hot_keys_btn_normal.png","images/mapHotKeyCurser.png","images/button_curser_map.png","images/map.png","images/heading_tab.png","images/info_icon.png","images/clear.png","images/downArrow.png","images/leftArrow.png","images/hotKey.png","images/back_normal.png","images/btn_curser.png","images/photo_image_box.png","images/map_bg.png","images/strip.png","images/accordion/acc_notick_mark.png","images/accordion/acc_tick_mark.png","images/accordion/tab_normal.png","images/accordion/tab_selected.png","images/accordion/tab_curser.png","images/accordion/acc_tick_disabled.png","images/accordion/district_normal.png","images/accordion/district_curser.png","images/more_curser.png","images/detail/cry.png","images/detail/happy.png","images/detail/ok.png","images/detail/grid_cursor.png","images/detail/image_bg.png","images/detail/default_image.png","images/listing/img_bg.png","images/listing/list_cursor.png","images/listing/list_bg.png"];for(var i=0;i<imagesBufArray.length;i++){imagesCode+="<img id ='buffer_'"+i+"class='bufferImg' src= "+imagesBufArray[i]+"></img>";}
document.getElementById("buffer").innerHTML=imagesCode;};global.bufferImages();global.getServer=function(param){return global.serverList[param];};global.splash=document.getElementById("splash");global.splash.On=function(){$("#splash").css("display","block");};global.splash.Off=function(){try{splashOn=false;$('body').css('background-image',"url(images/bg.png)");$("#splash").remove();}catch(e){}};global.getCookie=function(cookieName){var c_value=document.cookie;var c_start=c_value.indexOf(" "+cookieName+"=");if(c_start==-1){c_start=c_value.indexOf(cookieName+"=");}
if(c_start==-1){c_value=null;}else{c_start=c_value.indexOf("=",c_start)+1;var c_end=c_value.indexOf(";",c_start);if(c_end==-1){c_end=c_value.length;}
c_value=unescape(c_value.substring(c_start,c_end));}
return c_value;}
global.setCookie=function(cookieName,value,exdays){try{var exdate=new Date();exdate.setDate(exdate.getDate()+exdays);var c_value=escape(value)+((exdays==null)?"":"; expires="+exdate.toUTCString());document.cookie=cookieName+"="+c_value;}catch(e){}}
global.del_cookie=function(name){var c_value=document.cookie;document.cookie=c_value+'=; expires=Thu, 01 Jan 1970 00:00:01 GMT;';}
global.checkCookie=function(param){try{var param=param||"";var OR_Country_Cookie=global.getCookie("OR_Country");var OR_CityId_Cookie=global.getCookie("OR_CityId");var OR_CityName_Cookie=global.getCookie("OR_CityName");if(OR_Country_Cookie&&OR_CityId_Cookie&&OR_CityName_Cookie){if(param=="setCurrentLoc"){search.Selections.region.country=OR_Country_Cookie;search.Selections.region.city_Name[0]=OR_CityName_Cookie;search.Selections.region.city_Id[0]=OR_CityId_Cookie;global.location.set(search.Selections.region.country,search.Selections.region.city_Name[0]);global.cookieSet=true;}
return true;}else{return false;}}catch(e){}}
global.setUserRegion_Cookie=function(){global.setCookie("OR_Country",search.Selections.region.country,365);global.setCookie("OR_CityId",search.Selections.region.city_Id[0],365);global.setCookie("OR_CityName",search.Selections.region.city_Name[0],365);global.location.set(search.Selections.region.country,search.Selections.region.city_Name[0]);global.cookieSet=true;}
global.getUserRegionError=function(param){search.Selections.region.country="";search.Selections.region.city_Name[0]="";search.Selections.region.city_Id[0]="";global.disableSearch=true;document.getElementById("menuBtn_0").style.backgroundPosition="0 -1385px";document.getElementById("menuBtn_0").getTitle().style.color="rgba(255, 255, 255, 0.3)";}
global.showLocation=function(param){var param=param||"";global.getUserRegionError();region.createLocation((param!=""?param:""));}
global.resetSearchMenu=function(){global.disableSearch=false;document.getElementById("menuBtn_0").style.backgroundPosition="0 -831px";document.getElementById("menuBtn_0").getTitle().style.color="#cccccc";}
global.ArrowClass=function(){try{this.left=document.getElementById('downArrow');this.right=document.getElementById('upArrow');this.createArrow=function(param){var type=param||"up";if(type=="left"){this.left.className="leftArrowClass";this.right.className="rightArrowClass";}else{this.left.className="downArrowClass";this.right.className="upArrowClass";}};this.showArrow=function(param){this.left.style.backgroundPosition="0 0";this.right.style.backgroundPosition="0 0";switch(param){case"left":case"down":this.left.style.backgroundPosition="0 -50px";break;case"right":case"up":this.right.style.backgroundPosition="0 -50px";break;case"both":this.left.style.backgroundPosition="0 -50px";this.right.style.backgroundPosition="0 -50px";break;case"none":this.left.style.backgroundPosition="0 0";this.right.style.backgroundPosition="0 0";break;default:this.left.style.backgroundPosition="0 0";this.right.style.backgroundPosition="0 0";break}};}catch(e){}};global.showError=function(param,type,inList){var type=type||"dontClearBtm";var inList=(inList=="inList"?true:false);if($("#regionPopUp").length>0){clearTimeout(search.maxLimitTimerObj);$("#regionPopUp").remove();}
if($("#errorContent").length<=0){$("#innerSection").append("<div id='errorContent'><div id='errorIcon'></div><div id ='errorTextVal'>"+global.getError(param)+"</div></div>");if(type=="dontClearBtm"&&param!="listing"&&param!="network"){$("#errorContent").css("margin-top","265px");}else{$("#errorContent").css("margin-top","385px");if(param!="listing"&&type!="dontClearBtm"){$("#bottomSection").removeClass("bottomSectionBg");$("#bottomSection").html("");}else if(param=="listing"&&type=="clearBottom"){$("#bottomSection").removeClass("bottomSectionBg");$("#bottomSection").html("");}}}
if(inList){global.mainMenu.makeSelected(0);if(global.defaultSet){global.defaultSet=false;global.defaultSetpopUp.create("defaultSet",global.mainMenu);}else{if($("#HotKey_4").length>0){if(!listing.itemIsVisible()){listingHotKey.index=2;global.rigthNav=listingHotKey;}}else{global.rigthNav=null;}
global.mainMenu.enter_focus();}}}
global.getError=function(param){var str="";switch(param){case"defaultSet":str="The category listing is limited for Malaysia region; If you wish to search the restaurant in other regions, please go to \" My Location \" to change your setting and search again in the Application.";break;case"defaultSearch":str="Please select at least 1 search criteria for us <br/>to find your desired restaurant.";break;case"network":str="Unable to connect to the network.<br/> Please try again later.";break;case"location":str="No locations available.";break;case"search":str="No search criteria available.";break;case"listing":str="Sorry, your search returned no results.";break;case"detail":str="No details available.";break;case"district":str="No districts available.";break;case"cuisine":str="No cuisines available.";break;case"dish":str="No dish types available.";break;case"restaurant":str="No restaurant types available.";break;case"theme":str="No theme available.";break;case"price":str="No price available.";break;case"photos":str="No photos available.";break;case"map":str="No map available.";break;}
return str;}
global.defaultSetpopUp=(function(){var obj={};var returnObj=global.mainMenu||"";obj.create=function(param,param_returnObj){if($("#fullMask").length>0){$("#fullMask").remove();}
if($("#defaultSetPopUp").length>0){$("#defaultSetPopUp").remove();}
var fullMask="<div id = 'fullMask' class = 'fullMaskCls'></div>";var popUp="<div id='defaultSetPopUp'><div id ='infotxt'>"+global.getError(param)+"</div><div id='searchListError_Ok' class = 'normal'><div id='searchListError_OkInner'>OK</div></div></div>";$("#wrapper").append(fullMask);$('#wrapper').append(popUp);$('#searchListError_Ok').css("margin","16px 0px 0px 411px");returnObj=param_returnObj||global.mainMenu;obj.enter_focus("searchListError_Ok");}
obj.enter_focus=function(id){global.focusedDom=this;$("#"+id).attr("class","change");$("#"+id+"Inner").addClass("exitCurser");}
obj.leave_focus=function(id){$("#"+id).attr("class","normal");$("#"+id+"Inner").removeClass("exitCurser");}
obj.hide=function(){$("#defaultSetPopUp").remove();$("#fullMask").remove();returnObj.enter_focus();}
obj.KeyboardEvent=function(e,eventType){var target=_target(e),keyCode=target.keyCode,key=global.keyCodeDic[keyCode];switch(eventType){case"keydown":switch(key){case"ok":obj.hide();return true;break;case"return":e.preventDefault();obj.hide();return true;break;}
break;}};return obj;})();global.clearContents=function(){global.innerParent.innerHTML="";};global.createContents=function(type){var headerTitle="";if(type=="location"){global.innerParent.innerHTML="<div id='content'></div";headerTitle="Please select your location: ";}else{$("#innerSection").append("<div id='content'></div>");headerTitle=search.select[search.curMenu];}
document.getElementById("content").innerHTML="<div id='regionHeader'>"+headerTitle+"</div>"+"<div id='regionHeader_selectedText'></div>"+"<div id='categoryList'><div id='accordion'></div></div>";if(type!="location"){region.createClear();}
if(type=="location"){region.cat_height=800;$("#categoryList").css("height","800px");$("#categoryList").css("top","110px");$("#regionHeader").css("margin-top","44px");}else{region.cat_height=700;$("#categoryList").css("height","700px");$("#categoryList").css("top","175px");$("#regionHeader").css("margin-top","10px");}};global.createHotKey=function(){menu="";if(!$("#bottomSection").hasClass("bottomSectionBg"))
$("#bottomSection").addClass("bottomSectionBg");menu="<div id='hotKeyCont'><div id='hotKeyOuter_1'><div class='hotKeys' id='HotKey_1'><div id='redhotKeyImg' class='hotKeyImg' ></div><div id='label_1' class='hotKeyLabel'>Prev Menu</div></div></div><div id='hotKeyOuter_2'><div class='hotKeys' id='HotKey_2'><div id='greenhotKeyImg'  class='hotKeyImg'></div><div  id='label_2' class='hotKeyLabel'>Next Menu</div></div></div><div id='arrows'><div id='downArrow'></div><div id='upArrow'></div></div><div id='hotKeyOuter_3'><div class='hotKeys' id='HotKey_3'><div id='yellowhotKeyImg'  class='hotKeyImg' ></div><div  id='label_3' class='hotKeyLabel'>Reset</div></div></div><div id='hotKeyOuter_4'><div class='hotKeys' id='HotKey_4'><div id='bluehotKeyImg'  class='hotKeyImg' ></div><div  id='label_4' class='hotKeyLabel'>Search</div></div><div></div>";$("#bottomSection").html(menu);global.arrow=new global.ArrowClass();global.arrow.createArrow("up");global.arrow.showArrow("none");}
hotKeyObj.enter_focus=function(){global.focusedDom=this;$("#HotKey_"+hotKeyObj.hotKeyCur).addClass('hotKeyCurser');}
hotKeyObj.leave_focus=function(){$("#HotKey_"+hotKeyObj.hotKeyCur).removeClass('hotKeyCurser');}
hotKeyObj.KeyboardEvent=function(e,eventType){try{var target=_target(e),keyCode=target.keyCode,key=global.keyCodeDic[keyCode];switch(eventType){case"keydown":switch(key){case"arrowleft":hotKeyObj.leave_focus();hotKeyObj.hotKeyCur--;if($("#HotKey_"+hotKeyObj.hotKeyCur).length>0){hotKeyObj.enter_focus();}else{hotKeyObj.hotKeyCur=4;hotKeyObj.enter_focus();}
break;case"arrowright":hotKeyObj.leave_focus();hotKeyObj.hotKeyCur++;if($("#HotKey_"+hotKeyObj.hotKeyCur).length>0){hotKeyObj.enter_focus();}else{hotKeyObj.hotKeyCur=1;hotKeyObj.enter_focus();}
break;case"arrowup":if(($("#content").length>0)||($("#thumbnail").length>0)&&(region.accordionScreen!="location")){hotKeyObj.leave_focus();if(search.curMenu==0||search.curMenu==1){region.settoLastAcc();region.enter_focus();}else{search.curFocusMenu=search.curMenu;search.menuGridContainer.enter_focus();}}else if(global.screen==1){hotKeyObj.leave_focus();search.curFocusMenu=search.curMenu;search.searchMenuContainer.enter_focus(search.curFocusMenu);}
break;case"ok":try{hotKeyObj.leave_focus();switch(hotKeyObj.hotKeyCur){case 1:search.searchMenuContainer.menuEnter("left");break;case 2:search.searchMenuContainer.menuEnter("right");break;case 3:if($("#hotKeyOuter_3").css("color")!="rgb(196, 170, 151)"){search.clearAllScreen();}
break;case 4:listing.createSearchList("default");break;}}catch(e){}
break;}
break;}}catch(e){}};global.removeHotKey=function(type){menu="";if(!$("#bottomSection").hasClass("bottomSectionBg"))
$("#bottomSection").addClass("bottomSectionBg");menu="<div id='arrows'><div id='downArrow'></div><div id='upArrow'></div></div>";$("#bottomSection").html(menu);global.arrow=new global.ArrowClass();global.arrow.createArrow(type);global.arrow.showArrow("none");}
global.loading=document.getElementById("loading");global.loading.On=function(pos){global.loading.className="loading loadingOn";if(pos){global.loading.style.top=pos+"px";}else{global.loading.style.top="470px";}
global.loadOn=true;};global.loading.Off=function(){global.loadOn=false;global.loading.className="loading loadingOff";};global.firstSelTab=function(){var screenTab=search.curFocusMenu;return parseInt(screenTab);}
global.returnFunc=function(){if(global.gadget==-1){if(global.screen==2){global.clearContents();global.mainMenu.leave_focus();if(search.SearchAPIData.dataAvailability){search.showSearchScreen({"screen":global.firstSelTab(),"state":"init"});}else{search.createSearch();}}else if(global.screen==3){if($("#morePopUp").length>0){morePopUp.removeMorePopUp();}else{global.clearContents();detail.main.photoGrid.reset();listing.createSearchList("detail");}}else if(global.screen==4){detail.gridContainer.reset();global.mainMenu.leave_focus();detail.createDetail("photos");}else if(global.screen==5){global.clearContents();detail.mapContainer.free();$("#arrows").css("display","block");detail.createDetail("map");}else if(global.screen==0||global.screen==1){global.exitPopUpContainer.create();}}else if(global.gadget==1||global.gadget==2){if((global.screen==0)||(global.screen==2)||(global.gadget==2&&global.screen==3)){if($("#morePopUp").length>0){morePopUp.removeMorePopUp();}else{global.exitPopUpContainer.create();}}else if(global.screen==3){if($("#morePopUp").length>0){morePopUp.removeMorePopUp();}else{global.clearContents();listing.createSearchList("detail");}}else if(global.screen==4){detail.gridContainer.reset();detail.createDetail("photos");}else if(global.screen==5){global.clearContents();detail.curMapObj=1;$("#mask").remove();$("#mapControls").remove();$("#arrows").css("display","block");detail.createDetail("map");}}else{global.exitPopUpContainer.create();}}
document.onkeydown=function(e){MainKeyboardEvent(e,"keydown");};_target=function(e){!e&&(e=window.event);var target=(e.target||e.srcElement)||{};target.keyCode=e.which;return target;};MainKeyboardEvent=function(e,eventType){try{var target=_target(e),keyCode=target.keyCode,key=global.keyCodeDic[keyCode];if($("#regionPopUp").length>0){e.preventDefault();clearTimeout(search.maxLimitTimerObj);region.popUpHide();return;}
if(global.loadOn){e.preventDefault();return true;}
if(splashOn){return true;}
if($("#maxLimitPopUp").length>0){e.preventDefault();clearTimeout(search.maxLimitTimerObj);search.menuGridContainer.popUpHide();return;}
if(global.focusedDom.KeyboardEvent&&global.focusedDom.KeyboardEvent(e,eventType)){return true;}
if(($("#exitCont").length>0)||($("#searchListError").length>0)||($("#defaultSetPopUp").length>0)){return;}
switch(eventType){case"keydown":switch(key){case"yellow":if(($("#label_3").css("color")!="rgb(196, 170, 151)")&&(global.screen==1)){if((($("#content").length>0)||($("#thumbnail").length>0)||($("#menuCont").length>0))&&(region.accordionScreen!="location")){search.clearAllScreen();}}else if($("#errorContent").length==0&&global.screen==5){detail.map.panBy(-100,0);$("#cur_7").css("color","white");}
break;case"green":if((($("#content").length>0)||($("#thumbnail").length>0)||($("#menuCont").length>0))&&(region.accordionScreen!="location")){hotKeyObj.leave_focus();search.searchMenuContainer.menuEnter("right");}else if($("#errorContent").length==0&&global.screen==5){detail.map.panBy(0,100);$("#cur_7").css("color","white");}else if(global.screen==2){if($("#hotKeyOuter_2").length>0){$('#downArrow').removeClass("arrowAnim");$('#upArrow').removeClass("arrowAnim");if($("#greenhotKeyImg").css("opacity")=="1"){if(listing.currentPage!=listing.totalListPages){listingHotKey.leave_focus();listing.currentPage++;listing.currentItem=0;listing.main.free();$('#downArrow').addClass("arrowAnim");listing.getListing(listing.currentPage);}}}}
break;case"red":if((($("#content").length>0)||($("#thumbnail").length>0)||($("#menuCont").length>0))&&(region.accordionScreen!="location")){hotKeyObj.leave_focus();search.searchMenuContainer.menuEnter("left");return;}else if($("#errorContent").length==0&&global.screen==5){detail.map.panBy(0,-100);$("#cur_7").css("color","white");}else if(global.screen==2){if($("#hotKeyOuter_1").length>0){$('#downArrow').removeClass("arrowAnim");$('#upArrow').removeClass("arrowAnim");if($("#redhotKeyImg").css("opacity")=="1"){if(listing.currentPage!=1){listingHotKey.leave_focus();listing.currentPage--;listing.main.free();$('#upArrow').addClass("arrowAnim");listing.getListing(listing.currentPage,"hotKey");}}}}
break;case"blue":try{if(region.accordionScreen!="location"&&$("#hotKeyCont").children().length>0&&$("#morePopUp").length<=0){if(global.screen==1){listing.createSearchList("default");}else if((global.screen==2)||(global.screen==3)||(global.screen==4&&global.gadget!=2)){if(global.gadget==-1){global.clearContents();if(search.SearchAPIData.dataAvailability){search.showSearchScreen({"screen":global.firstSelTab(),"state":"init"});}else{search.createSearch();}}else if((global.gadget==1)||(global.gadget==2)){global.clearContents();search.createSearch("resetUserReg");}}}else if($("#errorContent").length==0&&global.screen==5){detail.map.panBy(100,0);$("#cur_7").css("color","white");}}catch(e){}
break;case"return":e.preventDefault();global.returnFunc();break;}
break;}}catch(e){}};global.location.set=function(region,city){var regionVal=region||"";var cityVal=city||"";var currentTxt=regionVal+", "+cityVal;if(regionVal.replace(/\s+/g,"").toLowerCase()==cityVal.replace(/\s+/g,"").toLowerCase()){currentTxt=regionVal;}else{if(currentTxt.length>20){currentTxt=regionVal+", </br>"+cityVal;}}
global.location.innerHTML=currentTxt;};getParameter=function(){var path=document.location.search;var match,pl=/\+/g,search=/([^&=]+)=?([^&]*)/g,decode=function(s){return decodeURIComponent(s.replace(pl," "));},query=path.substring(1);global.urlParams={};while(match=search.exec(query)){global.urlParams[decode(match[1])]=decode(match[2]);}};global.checkMYHomeScreen=function(){var hscountry=global.urlParams['hscountry']||"";if(hscountry.toString()==global.MY_HSData['countryCode']){return true;}else{return false;}}
var map=function(screen){switch(parseInt(screen,10)){case 0:try{global.gadget=-1;if(global.checkMYHomeScreen()){if(global.checkCookie("setCurrentLoc")){search.createSearch();}else{search.Selections.region.country=global.MY_HSData['countryName'];search.Selections.region.city_Name[0]=global.MY_HSData['cityName'];search.Selections.region.city_Id[0]=global.MY_HSData['cityId'];global.setUserRegion_Cookie();region.createLocation();}}else{if(global.checkCookie("setCurrentLoc")){search.createSearch();}else{global.showLocation();}}}catch(e){global.showLocation();}
break;case 1:global.gadget=1;try{var type=global.urlParams['type']||"";var id=global.urlParams['id']||"";var typename=global.urlParams['typename']||"";if(type&&id){if(type==1){search.Selections.cuisine.id["header_0_1"]=id;search.Selections.cuisine.name["header_0_1"]=typename;}else if(type==2){search.Selections.dish.id[0]=id;search.Selections.dish.name[0]=typename;}else if(type==3){search.Selections.restaurantType.id[0]=id;search.Selections.restaurantType.name[0]=typename;}else if(type==4){search.Selections.theme.id=id.toString();search.Selections.theme.name=typename.toString();}else{global.urlParams['type']="0";}}else{global.urlParams['type']="0";}
if(global.checkMYHomeScreen()){if(global.checkCookie()){var OR_Country_Cookie=global.getCookie("OR_Country");if(OR_Country_Cookie=="Malaysia"){global.checkCookie("setCurrentLoc")}else{search.Selections.region.country=global.MY_HSData['countryName'];search.Selections.region.city_Name[0]=global.MY_HSData['cityName'];search.Selections.region.city_Id[0]=global.MY_HSData['cityId'];global.setUserRegion_Cookie();global.defaultSet=true;}}else{search.Selections.region.country=global.MY_HSData['countryName'];search.Selections.region.city_Name[0]=global.MY_HSData['cityName'];search.Selections.region.city_Id[0]=global.MY_HSData['cityId'];global.setUserRegion_Cookie();}}else{if(!global.checkCookie("setCurrentLoc")){global.showLocation("dontReset");return;}}
global.clearContents();listing.createSearchList("default");}catch(e){global.showLocation();}
break;case 2:try{global.gadget=2;listing.selectedItem=global.urlParams['id']||"";if(global.checkMYHomeScreen()){search.Selections.region.country=global.MY_HSData['countryName'];search.Selections.region.city_Name[0]=global.MY_HSData['cityName'];search.Selections.region.city_Id[0]=global.MY_HSData['cityId'];global.location.set(search.Selections.region.country,search.Selections.region.city_Name[0]);if(!global.checkCookie()){global.setUserRegion_Cookie();}}else{if(!global.checkCookie("setCurrentLoc")){global.showLocation("dontReset");return;}}
detail.createDetail("default");}catch(e){global.showLocation();}
break;default:global.gadget=-1;if(global.checkCookie("setCurrentLoc")){search.createSearch();}else{if(global.checkMYHomeScreen()){search.Selections.region.country=global.MY_HSData['countryName'];search.Selections.region.city_Name[0]=global.MY_HSData['cityName'];search.Selections.region.city_Id[0]=global.MY_HSData['cityId'];global.location.set(search.Selections.region.country,search.Selections.region.city_Name[0]);search.createSearch();}else{global.showLocation();}}
break;}};global.createHtml=function(){try{getParameter();global.cookieSet=false;global.defaultSet=false;global.clearContents();if(typeof(global.urlParams['screen'])==='undefined'){try{if(global.checkCookie("setCurrentLoc")){search.createSearch();}else{global.showLocation();}}catch(e){}}else{map(global.urlParams['screen']);}}catch(e){}};global.exitPopUpContainer=(function(){var obj={};var prevCursor="";var index=0;obj.create=function(){try{prevCursor=global.focusedDom;obj.show();var fullMask="<div id = 'fullMask' class = 'fullMaskCls'></div>";var outer='<div id="exitCont"><div id ="exitText">Would you like to exit the application?</div><div id="buttonContainer"><div id="yes" class = "normal"><div id="yesInner">Yes</div></div><div id="no" class = "normal"><div id="noInner">No</div></div></div></div>';$("#wrapper").append(fullMask);$("#wrapper").append(outer);obj.enter_focus("yes");}catch(e){}}
obj.enter_focus=function(id){global.focusedDom=this;$("#"+id).attr("class","change");$("#"+id+"Inner").addClass("exitCurser");}
obj.leave_focus=function(id){$("#"+id).attr("class","normal");$("#"+id+"Inner").removeClass("exitCurser");}
obj.show=function(){switch(prevCursor){case search.searchMenuContainer:if($("#clearAll").hasClass("clearCursor")){search.row_col.leftRetVal="clear";search.searchMenuContainer.leave_focus_clear();}else{prevCursor.leave_focus(search.curFocusMenu);}
break;case search.menuGridContainer:if($("#price").hasClass("priceCursor")){search.row_col.leftRetVal="price";search.menuGridContainer.leave_focus_price();}else{prevCursor.leave_focus(search.row_col.row,search.row_col.col);}
break;case search:prevCursor=region;default:if(typeof prevCursor==='object'&&prevCursor.leave_focus)
prevCursor.leave_focus();break;}}
obj.hide=function(){index=0;try{$("#fullMask").remove();$("#exitCont").remove();switch(prevCursor){case search.searchMenuContainer:if(search.row_col.leftRetVal=="clear"){search.searchMenuContainer.enter_focus_clear();}else{prevCursor.enter_focus(search.curFocusMenu);}
break;case search.menuGridContainer:if(search.row_col.leftRetVal=="grid"){prevCursor.enter_focus();}else{search.menuGridContainer.enter_focus_price();}
break;case search:prevCursor=region;default:prevCursor.enter_focus();break;}}catch(e){}}
obj.KeyboardEvent=function(e,eventType){var target=_target(e),keyCode=target.keyCode,key=global.keyCodeDic[keyCode];switch(eventType){case"keydown":switch(key){case"arrowleft":if(index==1){obj.leave_focus("no");obj.enter_focus("yes");index=0;}else{obj.leave_focus("yes");obj.enter_focus("no");index=1;}
return true;break;case"arrowright":if(index==0){obj.enter_focus("no");obj.leave_focus("yes");index=1;}else{obj.enter_focus("yes");obj.leave_focus("no");index=0;}
return true;break;case"ok":if(index==0){window.history.back();}else{obj.hide();}
return true;break;case"return":e.preventDefault();obj.hide();return true;break;}
return false;}
return false;};return obj;})();global.Menu=function(param){var parent=document.getElementById("menu"),btn=document.createElement('div'),img=document.createElement('div'),cursor=document.createElement('div'),title=document.createElement('div'),textClass,obj={};btn.className="normalBtn";btn.id="menuBtn_"+param.id;btn.className="normalBtn";btn.style.backgroundPosition=(param.id===0)?"0 -831px":"0 -277px";cursor.id="menuBtnCursor_"+param.id;cursor.className="normalBtn menuCursor";textClass=(param.id===0)?" menuBtnSearchLabel":" menuBtnLocationLabel ";title.className="menuBtnLabel"+textClass;title.id="menuTitle"+param.id;title.innerHTML=(param.id===0)?"Search Restaurant":"My Location";btn.appendChild(title);btn.appendChild(cursor);parent.appendChild(btn);btn.setCursor=function(){cursor.style.visibility="visible";};btn.removeCursor=function(){cursor.style.visibility="hidden";};btn.getTitle=function(){return title;}};global.MenuClass=function(){var components=[],prevIndex=0,currIndex=0,total=0,selected=0;this.createMenu=function(){parent.innerHTML="";components=[];total=2;for(var i=0;i<total;i++){global.Menu({'id':i});};while(total--){id="menuBtn_"+total;components[total]=document.getElementById(id);};};this.createMenu();this.KeyboardEvent=function(e,eventType){try{var target=_target(e),keyCode=target.keyCode,key=global.keyCodeDic[keyCode];switch(eventType){case"keydown":switch(key){case"arrowup":if(!global.disableSearch){if(components[currIndex-1]){prevIndex=currIndex;components[prevIndex].removeCursor();this.animateOff(prevIndex);components[--currIndex].setCursor();this.animateOn(currIndex);}else{currIndex=components.length-1;components[0].removeCursor();this.animateOff(0);components[currIndex].setCursor();this.animateOn(currIndex);}}
return true;break;case"arrowdown":if(!global.disableSearch){if(components[currIndex+1]){prevIndex=currIndex;components[prevIndex].removeCursor();this.animateOff(prevIndex);components[++currIndex].setCursor();this.animateOn(currIndex);}else{currIndex=0;components[components.length-1].removeCursor();this.animateOff(components.length-1);components[currIndex].setCursor();this.animateOn(currIndex);}}
return true;break;case"ok":this.makeSelected(currIndex);if(currIndex==0){if(global.screen!=1){if(search.SearchAPIData.dataAvailability){search.showSearchScreen({"screen":global.firstSelTab(),"state":"init"});}else{search.createSearch("resetUserReg");}}}else{if(global.screen!=0){global.checkCookie("setCurrentLoc");region.createLocation();}}
break;case"arrowright":if($("#content").length>0){this.leave_focus();if(region.accordionScreen=="location"||search.curMenu==0||search.curMenu==1){region.enter_focus();}
return true;}else if(($("#thumbnail").length>0)&&(search.curMenu!=0||search.curMenu!=1)){this.leave_focus();search.menuGridContainer.enter_focus();}else if(region.accordionScreen!="location"&&(global.screen==1)&&($("#menuCont").length>0)){this.leave_focus();search.curFocusMenu=0;search.searchMenuContainer.enter_focus(search.curFocusMenu);}else if(($("#foodMenuCont").length>0)&&(global.screen==4)){this.leave_focus();detail.gridContainer.enter_focus(0);}else{if(global.rigthNav){this.leave_focus();global.rigthNav.enter_focus();}}
break;}
break;}}catch(e){}};this.animateOn=function(num){var selectedMenuIndex=((num==selected)?0:1);$(components[num].getTitle()).addClass("menuAnim"+selectedMenuIndex);}
this.animateOff=function(num){$(components[0].getTitle()).removeClass("menuAnim0");$(components[0].getTitle()).removeClass("menuAnim1");$(components[1].getTitle()).removeClass("menuAnim0");$(components[1].getTitle()).removeClass("menuAnim1");}
this.enter_focus=function(){global.focusedDom=this;components[selected].setCursor();this.animateOn(selected);};this.leave_focus=function(){components[currIndex].removeCursor();this.animateOff(currIndex);currIndex=selected;};this.makeSelected=function(value){try{(selected===0)?components[selected].style.backgroundPosition="0 -831px":components[selected].style.backgroundPosition="0 -277px";(value===0)?components[value].style.backgroundPosition="0 -1108px":components[value].style.backgroundPosition="0 -554px";components[selected].getTitle().style.color="#cccccc";components[value].getTitle().style.color="#4E3D2D";currIndex=selected=value;this.animateOff();this.animateOn(value);}catch(e){}};this.removeSelection=function(value){(selected===0)?components[selected].style.backgroundPosition="0 -831px":components[selected].style.backgroundPosition="0 -277px";components[value].getTitle().style.color="#cccccc";currIndex=selected=value;}
this.makeSelected(1);};global.mainMenu=new global.MenuClass();global.arrow=new global.ArrowClass();win.global=global;})(window);}catch(e){}