// Copyright (C) 2014 Open Rice & Panasonic Corporation. All Rights Reserved.
//
//****************************/
// File Name: region.js
// Purpose: This document creates my location screen with async true API
// File Created Date: 17-Oct-2013
// Release Date: 02-Jan-2014
// Release Version: 1.4
//****************************/
function toTitleCase(str){return str.replace(/\w\S*/g,function(txt){return txt.charAt(0).toUpperCase()+txt.substr(1).toLowerCase();});}
function isEmptyList(o){for(var p in o){if(o.hasOwnProperty(p)){return false;}}
return true;}
function removeHyphen(str){str=str.replace(/\--+$/,"");str=str.replace(/^\--+/,"");return str;}
try{var region={"accordion":{},"clear":{},"apiLoadCount":0,"regionListLength":0,"accordionScreen":"","apiData":{},"header_page":{},"header_index":0,"panel_index":0,"activeAccordion":0,"currentHeight":100,"headerHeight":100,"panelHeight":100,"rows":{},"maxRows":3,"maxCols":3,"prevCurType":"header","noOfAcc":0,"cat_height":800,};region.getRegions=function(param){try{global.loading.On();region.apiLoadCount=0;$.ajax({type:"GET",url:param.url,headers:{'or-token':global.OR_Token,},dataType:"json",timeout:30000,success:function(data,textStatus,xhr){try{region.apiLoadCount++;var feedValue=data;if(feedValue!=null&&feedValue.Root&&feedValue.Root.Data[0]){if(feedValue.Root.Data[0].Errors){region.apiData[param.countryName]=null;}else{region.apiData[param.countryName]=data;}}else{region.apiData[param.countryName]=null;}
region.callCreateLocationList();}catch(e){region.apiLoadCount++;region.apiData[param.countryName]=null;region.callCreateLocationList();}},error:function(jqXHR,textStatus,errorThrown){region.apiLoadCount++;region.apiData[param.countryName]=null;region.callCreateLocationList();}});}catch(e){region.apiLoadCount++;region.apiData[param.countryName]=null;region.callCreateLocationList();}}
region.createLocation=function(param){var param=param||"";if(param==""){global.screen=0;global.gadget=-1;}
region.regionListLength=0;for(var k in global.serverList){region.regionListLength++;var url=global.getServer(k.toString())+"/api/api.htm?method=or.code.getregion&api_token=apitoken&api_sig=apisignature&app_type=orpanasonic&response_type=json";region.getRegions({"url":url,"countryName":k.toString()});}}
region.callCreateLocationList=function(){if(region.apiLoadCount>=region.regionListLength){global.splash.Off();global.loading.Off();region.createLocationList();}}
region.totalPages=function(totalLength){var totalPages=((totalLength%(region.maxRows*region.maxCols))>0?(parseInt(totalLength/(region.maxRows*region.maxCols))+1):(totalLength/(region.maxRows*region.maxCols)));return totalPages;}
region.createArrow=function(index){try{var leftArrow=document.getElementById('leftAccArrow_'+index),rightArrow=document.getElementById('rightAccArrow_'+index),obj=this;obj.enableRightArrow=function(){rightArrow.style.backgroundPosition="0px -47px";};obj.enableLeftArrow=function(){leftArrow.style.backgroundPosition="0px -47px";};obj.enableBothArrow=function(){leftArrow.style.backgroundPosition="0px -47px";rightArrow.style.backgroundPosition="0px -47px";};obj.disableBothArrow=function(){leftArrow.style.backgroundPosition="0px 0px";rightArrow.style.backgroundPosition="0px 0px";};obj.hideArrow=function(){leftArrow.style.visibility="hidden";rightArrow.style.visibility="hidden";};obj.showArrow=function(){leftArrow.style.visibility="visible";rightArrow.style.visibility="visible";};obj.checkArrow=function(index,endIndex,listLength){obj.showArrow();obj.disableBothArrow();if(region.header_page["header_"+index]>1&&endIndex<listLength){obj.enableBothArrow();}else if(region.header_page["header_"+index]>1&&listLength<=endIndex){obj.enableLeftArrow();}else if((endIndex)<listLength){obj.enableRightArrow();}}}catch(e){}};region.getPanelRow=function(count){for(var loop=1;loop<=region.maxCols;loop++){if(count<=(loop*region.maxCols)){return loop;}}}
region.filterId=function(arr,checkValue){return arr.filter(function(obj){if(obj==checkValue)
return true;else
return false;});}
region.showSelected=function(arrlist,checkValue,index){var keyValue="header_"+index+"_"+region.header_page["header_"+index];if(arrlist.city_Id.length>0){if(region.filterId(arrlist.city_Id,checkValue)!="")
return true;}
return false;}
region.popUpCreate=function(){var popUp="<div id='regionPopUp' class= 'maxLimitPopUp'>Saving your location...</div>";if($("#regionPopUp").length>0){$("#regionPopUp").remove();}
$('body').append(popUp);search.maxLimitTimerObj=setTimeout(function(){region.popUpHide();},3000);};region.popUpHide=function(){$("#regionPopUp").fadeTo(1000,0,function(){$("#regionPopUp").remove();});}
region.selectLocItem=function(){try{var alreadySel=false;if($('#panelCur_'+region.activeAccordion+"_"+region.panel_index).hasClass("panelLoc-selected")){alreadySel=true;}
$('#panelCur_'+region.activeAccordion+"_"+region.panel_index).addClass("panelLoc-selected");if(!alreadySel){region.popUpCreate();}
global.resetSearchMenu();search.Selections.region.country=$('#header_'+region.activeAccordion).text().toString();search.Selections.region.city_Id[0]=$('#panel_'+region.activeAccordion+"_"+region.panel_index).attr("data-mydata").toString();search.Selections.region.city_Name[0]=$('#panel_'+region.activeAccordion+"_"+region.panel_index).text().toString();global.setUserRegion_Cookie();global.urlParams['hscountry']="";if(global.gadget==1){global.clearContents();listing.createSearchList("default");}else if(global.gadget==2){detail.createDetail("default");}else{if(alreadySel&&search.SearchAPIData.dataAvailability){search.showSearchScreen({"screen":global.firstSelTab(),"state":"init"});}else{search.createSearch();}}}catch(e){}}
region.setPanelHeight=function(){$('#panel_'+region.activeAccordion).css("height",(region.maxRows*100)+"px");}
region.createPanelData=function(param){try{var feedValue="";var index=param.index;var nameList=param.Name;var idList=param.Id;var startIndex=endIndex=item=0;if(param.dir=="init"){startIndex=(region.header_page["header_"+index]==1?0:((region.header_page["header_"+index]*region.maxRows*region.maxCols)-(region.maxRows*region.maxCols)));endIndex=(region.header_page["header_"+index]*region.maxRows*region.maxCols);}else if(param.dir=="right"){if((region.header_page["header_"+index]*region.maxRows*region.maxCols)<idList.length){startIndex=(region.header_page["header_"+index]*region.maxRows*region.maxCols);region.header_page["header_"+index]++;endIndex=(region.header_page["header_"+index]*region.maxRows*region.maxCols);}}else{if(region.header_page["header_"+index]>1){region.header_page["header_"+index]--;startIndex=(region.header_page["header_"+index]*region.maxRows*region.maxCols)-(region.maxRows*region.maxCols);endIndex=(region.header_page["header_"+index]*region.maxRows*region.maxCols);}}
var addCls=titleCls="",listArray="";if(region.accordionScreen=="location"){addCls="item";titleCls="locationTitle";listArray=search.Selections.region;}else if(region.accordionScreen=="district"||region.accordionScreen=="cuisine"){if(region.accordionScreen=="district")
listArray=search.Selections.district;else if(region.accordionScreen=="cuisine")
listArray=search.Selections.cuisine;titleCls="searchTitle";}
for(var loopVar=startIndex;loopVar<(endIndex>idList.length?idList.length:endIndex);loopVar++){var itemTitle=toTitleCase(nameList[loopVar]);if(region.accordionScreen=="location"){if(region.showSelected(listArray,idList[loopVar],index)&&global.cookieSet){addCls="item panelLoc-selected";region.header_index=index;}else{addCls="item";}}else if(region.accordionScreen=="district"||region.accordionScreen=="cuisine"){if((region.accordionScreen=="cuisine")&&(typeof search.Selections.cuisine.headerWithGroupSel["header_"+index]!=='undefined')&&(search.Selections.cuisine.headerWithGroupSel["header_"+index])){if(loopVar==0)
addCls="panelDis-selected";else
addCls="panelDis-disable";}else{if(search.showSelected(listArray,idList[loopVar],index)){addCls="panelDis-selected";}else{addCls="districtItem";}}}
feedValue+="<div id = 'panelCur_"+index+"_"+loopVar+"' class='"+addCls+"' ><div id = 'panel_"+index+"_"+loopVar+"' data-mydata ="+idList[loopVar]+" ><div class ="+titleCls+">"+itemTitle+"</div></div></div>";if(param.dir=="init")
item++;}
if(region.accordionScreen!="location"&&listArray.noOfSelection>0){region.clear.show();$('#regionHeader_selectedNo').text(listArray.noOfSelection.toString());}
if(document.getElementById('panel_'+index)&&(feedValue!="")){region.leave_focus("panel");document.getElementById('panel_'+index).innerHTML="";var feed="<div id='leftAccArrow_"+index+"' class='leftAccArrowClass' style= 'margin-top:"+(((region.rows["header_"+index]-1)*50)+15)+"px;'></div>";feed+=feedValue;feed+="<div id='rightAccArrow_"+index+"' class='rightAccArrowClass' style= 'margin-top:"+(((region.rows["header_"+index]-1)*50)+5)+"px;'></div>";feed+="<div id='pagination_"+index+"' class='pagination'>"+region.header_page["header_"+index]+" of "+region.totalPages(idList.length)+"</div>";document.getElementById('panel_'+index).innerHTML=feed;region.setPanelHeight();region.createArrow(index);region.checkArrow(index,endIndex,idList.length);if(param.dir=="left"){region.panel_index=startIndex+2;region.currentHeight=((region.activeAccordion+1)*region.headerHeight)+region.panelHeight;}else if(param.dir=="right"){region.panel_index=startIndex;region.currentHeight=((region.activeAccordion+1)*region.headerHeight)+region.panelHeight;}
region.enter_focus("panel");return feedValue;}else if(feedValue!=""){region.panel_index=0;region.rows["header_"+index]=region.getPanelRow(item);var feed=feedValue;if((endIndex)<idList.length){feed="<div id='leftAccArrow_"+index+"' class='leftAccArrowClass' style= 'margin-top:"+(((region.rows["header_"+index]-1)*50)+15)+"px;'></div>";feed+=feedValue;feed+="<div id='rightAccArrow_"+index+"' class='rightAccArrowClass arrowNormal' style= 'margin-top:"+(((region.rows["header_"+index]-1)*50)+5)+"px;'></div>";feed+="<div id='pagination_"+index+"' class='pagination'>"+region.header_page["header_"+index]+" of "+region.totalPages(idList.length)+"</div>";}
return feed;}else{if(param.dir=="left"){region.leave_focus("panel");global.mainMenu.enter_focus();}
return"";}}catch(e){}}
region.createAccordion=function(param){try{var index=param.index;var errorText=param.error||"data";var headerName=param.headerName;var headerId=param.headerId;var idList=param.data.Id;var nameList=param.data.Name;headerName=removeHyphen(headerName);var className="";if(region.accordionScreen=="district"){if(search.Selections.district.headerSelected["header_"+index]){className="headerStarCls";}}else if(region.accordionScreen=="cuisine"){if(search.Selections.cuisine.headerSelected["header_"+index]){className="headerStarCls";}}
var feed="<h3><div id = 'header_"+index+"' data-mydata ="+headerId+"><div class ='headerTitle'>"+toTitleCase(headerName)+"</div><div id ='headerStar_"+index+"' class="+className+"></div></div></h3><div><div id= 'panel_"+index+"' class= 'panel'>";if(idList.length>0){region.header_page["header_"+index]=1;feed+=region.createPanelData({"index":index,"dir":"init","Id":idList,"Name":nameList});}else{region.header_page["header_"+index]=0;feed+="No "+errorText+" available.";}
feed+="</div></div>";return feed;}catch(e){}}
region.createClear=function(){document.getElementById("regionHeader_selectedText").innerHTML="Selected: "+"<div id='acc_clear'>"+"<div id='acc_clearCross' class= ''></div>"+"<div id='acc_clearCur' class= ''></div></div>"+"<div id='regionHeader_selectedNo'></div>";}
region.clear.show=function(){$('#regionHeader_selectedText').css("display","block");$('#regionHeader_selectedNo').css("display","block");$("#acc_clear").css("display","block");$("#acc_clearCross").css("display","block");$("#acc_clearCur").css("display","block");region.clear.setCrossMark();}
region.clear.remove=function(){$('#regionHeader_selectedText').css("display","none");$('#regionHeader_selectedNo').css("display","none");$("#acc_clear").css("display","none");$("#acc_clearCross").css("display","none");$("#acc_clearCur").css("display","none");}
region.clear.enter_focus=function(){global.focusedDom=region.clear;document.getElementById("acc_clearCur").className="acc_clearCurCls";}
region.clear.leave_focus=function(){document.getElementById("acc_clearCur").className="";}
region.clear.setCrossMark=function(){document.getElementById("acc_clearCross").className="acc_clearCrossCls";}
region.clear.removeCrossMark=function(){document.getElementById("acc_clearCross").className="";}
region.clear.KeyboardEvent=function(e,eventType){var target=_target(e),keyCode=target.keyCode,key=global.keyCodeDic[keyCode];switch(eventType){case"keydown":switch(key){case"arrowup":region.clear.leave_focus();search.curFocusMenu=search.curMenu;search.searchMenuContainer.enter_focus(search.curMenu);break;case"arrowdown":region.clear.leave_focus();region.set_focus();break;case"ok":if(search.curMenu==0){search.deSelectAll_Distirct();}else if(search.curMenu==1){search.deSelectAll_Cuisine();}
region.clear.leave_focus();region.set_focus();break;}
return false;}
return false;}
region.settoLastAcc=function(){region.currentHeight=((region.noOfAcc)*region.panelHeight);if(region.activeAccordion!==false){var checkrow=(region.header_page["header_"+region.activeAccordion]>1?((region.panel_index+1)-((region.header_page["header_"+region.activeAccordion]-1)*region.maxRows*region.maxCols)):(region.panel_index+1));var currentRow=region.getPanelRow(checkrow);region.currentHeight+=(currentRow*region.panelHeight);}
var margin=parseInt($("#accordion").css("margin-top"));if((region.currentHeight>region.cat_height)&&(margin==0)){var difference=(region.currentHeight-region.cat_height);global.loadOn=true;$("#accordion").stop().animate({"marginTop":"-="+(difference)+"px"},"normal",function(){global.loadOn=false;});}else{global.loadOn=false;}}
region.arr=function(param){param=param||"";global.arrow.createArrow("up");region.activeAccordion=$("#accordion").accordion("option","active");var acc_hei=((region.noOfAcc)*region.panelHeight);var cat_hei=region.cat_height;var margin=parseInt($("#accordion").css("margin-top"));global.arrow.showArrow("both");var total=region.currentHeight;if(region.activeAccordion!==false){acc_hei+=(region.rows["header_"+region.activeAccordion]*region.panelHeight);}
if(acc_hei<=cat_hei){if(margin<0)
global.arrow.showArrow("up");else
global.arrow.showArrow("none");}else if(param=="activating"){if(region.activeAccordion!==false){total+=(region.rows["header_"+region.activeAccordion]*region.panelHeight);}
if((total<acc_hei)&&(margin==0)){global.arrow.showArrow("down");}else if((margin<0)&&(total>=acc_hei)){global.arrow.showArrow("up");}}else if((total<acc_hei)&&(margin==0)){global.arrow.showArrow("down");}else if((margin<0)&&(total>=acc_hei)){global.arrow.showArrow("up");}else if((margin<0)&&((acc_hei+margin)<=cat_hei)){global.arrow.showArrow("up");}
global.loadOn=false;}
region.checkAllRegionStatus=function(){var index=0;for(var k in global.serverList){if(region.apiData[k]==null)
index++;else
break;}
if(index>=region.regionListLength)
return true;else
return false;}
region.createLocationList=function(){try{global.clearContents();if(region.checkAllRegionStatus()){if(!global.checkCookie()){global.getUserRegionError();}
global.mainMenu.enter_focus();global.rigthNav=null;global.showError("network","clearBottom");return false;}
global.createContents("location");global.removeHotKey("up");global.arrow.showArrow("none");region.accordion=document.getElementById("accordion");region.accordionScreen="location";var index=0;var feed="";region.header_index=0;region.panel_index=0;search.Selections.region.headerSelected={};for(var k in global.serverList){try{var idArray=[];var nameArray=[];if(region.apiData[k]!=null&&region.apiData[k].Root&&region.apiData[k].Root.Data[0]&&region.apiData[k].Root.Data[0].Regions&&region.apiData[k].Root.Data[0].Regions[0]){var reg=k.toString();for(var l in region.apiData[k].Root.Data[0].Regions[0].Region){idArray[l]=region.apiData[k].Root.Data[0].Regions[0].Region[l].RegionId;nameArray[l]=region.apiData[k].Root.Data[0].Regions[0].Region[l].NameLang1;}
if((reg.replace(/\s+/g,"").toLowerCase()==search.Selections.region.country.replace(/\s+/g,"").toLowerCase())){if(global.cookieSet){search.Selections.region.headerSelected["header_"+index]=true;}
region.header_index=index;}}
region.apiData["idArray_"+index]=idArray;region.apiData["nameArray_"+index]=nameArray;feed+=region.createAccordion({"index":index,"headerName":k.toString(),"headerId":index,"error":"cities","data":{"Id":region.apiData["idArray_"+index],"Name":region.apiData["nameArray_"+index]}});index++;}catch(e){}}
region.noOfAcc=index;region.accordion.innerHTML=feed;if((typeof search.Selections.region.headerSelected["header_"+region.header_index]!=='undefined')&&(search.Selections.region.headerSelected["header_"+region.header_index])){if(parseInt($('#panel_'+region.header_index+' > div').size())>0){$("#headerStar_"+region.header_index).addClass("headerStarCls");}}
region.setAccordion();global.focusedDom=region;region.arr();}catch(e){}}
region.set_focus=function(){region.prevCurType="header";region.currentHeight=100;global.mainMenu.leave_focus();region.enter_focus(region.prevCurType);}
region.enter_focus=function(type){if(region.accordionScreen=="location")
global.focusedDom=this;else if(region.accordionScreen=="district"||region.accordionScreen=="cuisine")
global.focusedDom=search;region.activeAccordion=$("#accordion").accordion("option","active");if(type)
region.prevCurType=type;if(region.prevCurType=="header"){$('#header_'+region.header_index).addClass("header-cursor");}else{$('#panel_'+region.activeAccordion+"_"+region.panel_index).addClass("panel-cursor");}}
region.leave_focus=function(type){region.activeAccordion=$("#accordion").accordion("option","active");if(type)
region.prevCurType=type;if(region.prevCurType=="header"){$('#header_'+region.header_index).removeClass("header-cursor");}else{$('#panel_'+region.activeAccordion+"_"+region.panel_index).removeClass("panel-cursor");}}
region.scrollDown=function(){try{var diff=region.currentHeight+parseInt($("#accordion").css("marginTop"));if((region.currentHeight>region.cat_height)&&diff>region.cat_height){var move=region.headerHeight;global.loadOn=true;$('#downArrow').addClass("arrowAnim");$("#accordion").stop().animate({"marginTop":"-="+move+"px"},"normal",function(){global.loadOn=false;region.arr();});}else{global.loadOn=false;}}catch(e){global.loadOn=false;}}
region.scrollUp=function(move){try{if(parseInt($("#accordion").css("marginTop"))<0){var upNav=(-parseInt($("#accordion").css("marginTop")));var diff=region.currentHeight+parseInt($("#accordion").css("marginTop"));if(region.currentHeight<=upNav&&(diff<=0)){var move=move||region.headerHeight;global.loadOn=true;$('#upArrow').addClass("arrowAnim");$("#accordion").stop().animate({"marginTop":"+="+move+"px"},"normal",function(){global.loadOn=false;region.arr();});}else{global.loadOn=false;}}else{global.loadOn=false;}}catch(e){global.loadOn=false;}}
region.downKey=function(){try{global.loadOn=true;$('#downArrow').removeClass("arrowAnim");$('#upArrow').removeClass("arrowAnim");var downAvailable=false;if($('#header_'+region.activeAccordion).hasClass("header-cursor")&&document.getElementById('panel_'+region.activeAccordion+"_"+region.panel_index)){region.header_index=region.activeAccordion;region.leave_focus("header");region.currentHeight+=(region.panelHeight);region.enter_focus("panel");downAvailable=true;region.scrollDown();}else if($('#panel_'+region.activeAccordion+"_"+region.panel_index).hasClass("panel-cursor")){var index=region.panel_index;if(document.getElementById('panel_'+region.activeAccordion+"_"+(index+region.maxCols))){region.leave_focus("panel");region.panel_index=(index+region.maxCols);region.currentHeight+=(region.panelHeight);region.enter_focus("panel");downAvailable=true;region.scrollDown();}else{var size=0;if(document.getElementById("leftAccArrow_"+region.activeAccordion)){size=parseInt($('#panel_'+region.activeAccordion+' > div').size())-4;}else{size=parseInt($('#panel_'+region.activeAccordion+' > div').size())-1;}
var index=region.header_index=region.activeAccordion;var checkrow=(region.header_page["header_"+region.activeAccordion]>1?((region.panel_index+1)-((region.header_page["header_"+region.activeAccordion]-1)*region.maxRows*region.maxCols)):(region.panel_index+1));var currentRow=region.getPanelRow(checkrow);var lastIndex=(region.header_page["header_"+region.activeAccordion]>1?(size+(region.header_page["header_"+region.activeAccordion]-1)*region.maxRows*region.maxCols):size);var checkrow=(region.header_page["header_"+region.activeAccordion]>1?((lastIndex+1)-((region.header_page["header_"+region.activeAccordion]-1)*region.maxRows*region.maxCols)):(lastIndex+1));var availableLastRow=region.getPanelRow(checkrow);if((currentRow<region.rows["header_"+index])&&document.getElementById('panel_'+region.activeAccordion+"_"+(region.panel_index+1))&&currentRow<availableLastRow){region.leave_focus("panel");region.panel_index=(region.header_page["header_"+region.activeAccordion]>1?(size+(region.header_page["header_"+region.activeAccordion]-1)*region.maxRows*region.maxCols):size);region.currentHeight+=(region.panelHeight);region.enter_focus("panel");downAvailable=true;region.scrollDown();}else if(document.getElementById('header_'+(index+1))){if(currentRow<region.rows["header_"+index]){region.currentHeight+=((region.rows["header_"+index]-currentRow)*(region.panelHeight))}
region.leave_focus("panel");region.header_index=(index+1);region.currentHeight+=(region.headerHeight);region.enter_focus("header");downAvailable=true;region.scrollDown();}}}else if($('#header_'+region.header_index).hasClass("header-cursor")){var index=region.header_index;if(document.getElementById('header_'+(index+1))){region.leave_focus("header");region.header_index=(index+1);region.currentHeight+=region.headerHeight;region.enter_focus("header");downAvailable=true;region.scrollDown();}}
if((region.accordionScreen!="location")&&(!downAvailable)){region.leave_focus(region.prevCurType);hotKeyObj.enter_focus();global.loadOn=false;}
if(!downAvailable){global.loadOn=false;}
$("#accordion").accordion("refresh");}catch(e){global.loadOn=false;}};region.upKey=function(){try{global.loadOn=true;$('#downArrow').removeClass("arrowAnim");$('#upArrow').removeClass("arrowAnim");var upAvailable=false;if($('#header_'+region.activeAccordion).hasClass("header-cursor")){var index=region.header_index=region.activeAccordion;if(document.getElementById('header_'+(index-1))){region.leave_focus("header");region.header_index=(index-1);region.currentHeight-=region.headerHeight;region.enter_focus("header");upAvailable=true;region.scrollUp();}else if(region.activeAccordion==0){if(region.accordionScreen!="location"){region.leave_focus("header");if(($("#acc_clear").css("display"))=="block"){region.clear.enter_focus();}else{search.curFocusMenu=search.curMenu;search.searchMenuContainer.enter_focus(search.curMenu);}}
global.loadOn=false;}}else if($('#panel_'+region.activeAccordion+"_"+region.panel_index).hasClass("panel-cursor")){var index=region.panel_index;if(document.getElementById('panel_'+region.activeAccordion+"_"+(index-region.maxCols))){region.leave_focus("panel");region.panel_index=(index-region.maxCols);region.currentHeight-=(region.panelHeight);region.enter_focus("panel");upAvailable=true;region.scrollUp();}else{region.header_index=region.activeAccordion;region.leave_focus("panel");region.currentHeight-=(region.panelHeight);region.enter_focus("header");upAvailable=true;region.scrollUp();}}else if($('#header_'+region.header_index).hasClass("header-cursor")){var index=region.header_index;if(document.getElementById('header_'+(index-1))&&(region.activeAccordion!=(index-1))){region.leave_focus("header");region.header_index=(index-1);region.currentHeight-=region.headerHeight;region.enter_focus("header");upAvailable=true;region.scrollUp();}else{if(document.getElementById('panel_'+region.activeAccordion+"_"+(region.panel_index))&&(region.activeAccordion==(index-1))){var checkrow=(region.header_page["header_"+region.activeAccordion]>1?((region.panel_index+1)-((region.header_page["header_"+region.activeAccordion]-1)*region.maxRows*region.maxCols)):(region.panel_index+1));var currentRow=region.getPanelRow(checkrow);if(currentRow<region.rows["header_"+(index-1)]){region.currentHeight-=((region.rows["header_"+(index-1)]-currentRow)*(region.panelHeight));}
region.leave_focus("header");region.currentHeight-=(region.headerHeight);region.enter_focus("panel");upAvailable=true;if(currentRow<region.rows["header_"+(index-1)]){region.scrollUp((region.rows["header_"+(index-1)]*region.headerHeight));}else{region.scrollUp();}}else if(document.getElementById('header_'+(index-1))){region.leave_focus("header");region.header_index=(index-1);region.currentHeight-=region.headerHeight;region.enter_focus("header");upAvailable=true;region.scrollUp();}else if(region.header_index==0){if(region.accordionScreen!="location"){region.leave_focus("header");if(($("#acc_clear").css("display"))=="block"){region.clear.enter_focus();}else{search.curFocusMenu=search.curMenu;search.searchMenuContainer.enter_focus(search.curMenu);}}
global.loadOn=false;}}}
if(!upAvailable){global.loadOn=false;}
$("#accordion").accordion("refresh");}catch(e){global.loadOn=false;}}
region.KeyboardEvent=function(e,eventType){try{var target=_target(e),keyCode=target.keyCode,key=global.keyCodeDic[keyCode];region.activeAccordion=$("#accordion").accordion("option","active");if(global.loadOn){e.preventDefault();return true;}
switch(eventType){case"keydown":switch(key){case"arrowdown":region.downKey();return true;break;case"arrowup":region.upKey();return true;break;case"ok":if($('#header_'+region.header_index).hasClass("header-cursor")){((region.activeAccordion===region.header_index)?(function(){$("#accordion").accordion({active:false});region.arr();})():(function(){$("#accordion").accordion({active:region.header_index});region.arr();})());}else{region.selectLocItem();}
return true;break;case"arrowleft":if($('#header_'+region.header_index).hasClass("header-cursor")){region.leave_focus("header");global.mainMenu.enter_focus();}else{var index=((region.panel_index%region.maxCols)>0?(region.panel_index-1):-1);if(document.getElementById('panel_'+region.activeAccordion+"_"+(index))&&(index>-1)){region.leave_focus("panel");region.panel_index=index;region.enter_focus("panel");}else{region.createPanelData({"index":region.activeAccordion,"dir":"left","Id":region.apiData["idArray_"+region.activeAccordion],"Name":region.apiData["nameArray_"+region.activeAccordion]});}}
return true;break;case"arrowright":if($('#header_'+region.header_index).hasClass("header-cursor")){}
else{var index=((region.panel_index%region.maxCols)!=(region.maxCols-1)?(region.panel_index+1):-1);if(document.getElementById('panel_'+region.activeAccordion+"_"+(index))&&(index>-1)){region.leave_focus("panel");region.panel_index=index;region.enter_focus("panel");}else{region.createPanelData({"index":region.activeAccordion,"dir":"right","Id":region.apiData["idArray_"+region.activeAccordion],"Name":region.apiData["nameArray_"+region.activeAccordion]});}}
return true;break;}
return false;}
return false;}catch(e){}};region.setAccordion=function(){try{$("#accordion").accordion({"icons":null,"active":region.header_index,"heightStyle":"content","collapsible":true,"animate":false,"activate":function(event,ui){region.activeAccordion=$("#accordion").accordion("option","active");if(region.header_page["header_"+region.header_index]){region.panel_index=((region.header_page["header_"+region.header_index]-1)*region.maxRows*region.maxCols)}
if(region.activeAccordion!==false){region.currentHeight=((region.activeAccordion+1)*region.headerHeight);var tempHeight=((region.activeAccordion+1)*region.headerHeight)+parseInt($("#accordion").css("marginTop"));var totalHieght=tempHeight+(region.rows["header_"+region.activeAccordion]*region.panelHeight);region.header_index=region.activeAccordion;if(tempHeight<0){var cur=parseInt($("#accordion").css("marginTop"));cur-=(tempHeight-region.headerHeight);$("#accordion").css("marginTop",(cur+"px"))}
if(totalHieght>region.cat_height){var move=totalHieght-region.cat_height;global.loadOn=true;$("#accordion").stop().animate({"marginTop":"-="+(move)+"px"},"normal",function(){region.currentHeight=((region.activeAccordion+1)*region.headerHeight);global.loadOn=false;region.arr("activating");});}else{global.loadOn=false;}}}});$("#accordion").accordion("refresh");region.set_focus();}catch(e){}}}catch(e){}