// Copyright (C) 2014 Open Rice & Panasonic Corporation. All Rights Reserved.
//
//****************************/
// File Name: restaurant_listing.js
// Purpose: This document creates restaurant listing page with async true API
// File Created Date: 17-Oct-2013
// Release Date: 02-Jan-2014
// Release Version: 1.4
//****************************/
var listing={'selectedItem':null,'currentItem':0,'currentPage':1,"totalListPages":0,'main':{}};var listingHotKey={"index":2};listing.resetVar=function(){listing.currentItem=0;listing.currentPage=1;}
listing.getSearchSelectionsName=function(){var districtName="",cuisineName="",selectionText="";for(var k in search.Selections.district.name){if(search.Selections.district.name[k]!="")
districtName+=search.Selections.district.name[k]+", ";}
if(districtName.length>0){districtName=districtName.slice(0,districtName.length-2);}
for(var k in search.Selections.cuisine.name){if(search.Selections.cuisine.name[k]!="")
cuisineName+=search.Selections.cuisine.name[k]+", ";}
if(cuisineName.length>0)
cuisineName=cuisineName.slice(0,cuisineName.length-2);if(districtName!="")
selectionText+=districtName;if(cuisineName!="")
selectionText+=(selectionText!=""?(", "+cuisineName):cuisineName);if(search.Selections.dish.name.length>0)
selectionText+=(selectionText!=""?(", "+search.Selections.dish.name):search.Selections.dish.name);if(search.Selections.restaurantType.name.length>0)
selectionText+=(selectionText!=""?(", "+search.Selections.restaurantType.name):search.Selections.restaurantType.name);if(search.Selections.theme.name.length>0)
selectionText+=(selectionText!=""?(", "+search.Selections.theme.name):search.Selections.theme.name);if(search.Selections.price.name.length>0)
selectionText+=(selectionText!=""?(", "+search.Selections.price.name):search.Selections.price.name);return selectionText;}
listing.getSearchSelectionsId=function(){var districtId="",cuisineId="",selections="";for(var k in search.Selections.district.id){if(search.Selections.district.id[k]!="")
districtId+=search.Selections.district.id[k]+",";}
if(districtId.length>0){districtId=districtId.slice(0,districtId.length-1);}
for(var k in search.Selections.cuisine.id){if(search.Selections.cuisine.id[k]!="")
cuisineId+=search.Selections.cuisine.id[k]+",";}
if(cuisineId.length>0){cuisineId=cuisineId.slice(0,cuisineId.length-1);}
if(districtId!="")
selections+="&district_id="+districtId;if(cuisineId!="")
selections+="&cuisine_id="+cuisineId;if(search.Selections.dish.id.length>0)
selections+="&dish_id="+search.Selections.dish.id
if(search.Selections.restaurantType.id.length>0)
selections+="&amenity_id="+search.Selections.restaurantType.id
if(search.Selections.theme.id.length>0&&search.Selections.theme.id!="")
selections+="&theme_id="+search.Selections.theme.id
if(search.Selections.price.id.length>0&&search.Selections.price.id!="")
selections+="&price_range_id="+search.Selections.price.id;return selections;};listing.createUrl=function(page){var page=page||1;var selections=listing.getSearchSelectionsId();var condition="";if(global.checkMYHomeScreen()){condition="&condition=halal";}
if(selections==""){if(global.screen==1){search.showSearchListError.create("defaultSearch");}else{global.showError("defaultSearch","dontClearBtm","inList");}
return false;}
var url=global.getServer(search.getSelections({"category":"region","type":"country"}))+"/api/api.htm?method=or.poi.getlist&region_id="+search.getSelections({"category":"region","type":"city_Id"})+selections+(condition!=""?condition:"")+"&page="+page+"&per_page=4&api_token=apitoken&api_sig=apisignature&app_type=orpanasonic&response_type=json&api_ver=&keyword=&lang=&Misc=&reloadcache=0&ret_info=&search_type=";return url;}
listing.createSearchList=function(from){try{global.mainMenu.leave_focus();if(global.screen!=1){global.screen=2;global.clearContents();if(global.gadget==1){if($("#regionPopUp").length>0){clearTimeout(search.maxLimitTimerObj);region.popUpHide();}
var type=global.urlParams['type']||"";var id=global.urlParams['id']||"";if(type=="0"||id==0||type==""||id==""||search.Selections.region.country==""||search.Selections.region.city_Name[0]==""||search.Selections.region.city_Id[0]==""){global.splash.Off();global.loading.Off();global.showError("listing","clearBottom","inList");if(search.Selections.region.country==""||search.Selections.region.city_Name[0]==""||search.Selections.region.city_Id[0]=="")
global.mainMenu.removeSelection(1);return;}
if(search.Selections.region.country!=""&&search.Selections.region.city_Name[0]!=""&&search.Selections.region.city_Id[0]!=""){listing.main=new listing.createHTMl();global.removeHotKey("up");listingHotKey.create({"type":"Search"});}}else{listing.main=new listing.createHTMl();global.removeHotKey("up");listingHotKey.create({"type":"Refine Search"});}}
if(from&&from=="default"){listing.resetVar();}else{global.mainMenu.leave_focus();}
listing.getListing(listing.currentPage);}catch(e){}};listing.itemIsVisible=function(){if(listing.main.components.length>0)
return true;else
return false;}
listingHotKey.create=function(param){var menu="";listingHotKey.index=2;menu="<div id='hotKeyCont'><div id='arrows'><div id='downArrow'></div><div id='upArrow'></div></div><div id='hotKeyOuter_4'><div class='hotKeys' id='HotKey_4'><div id='bluehotKeyImg'  class='hotKeyImg' ></div><div  id='label_4' class='hotKeyLabel'>";menu+=((param.type?param.type:"Search")+"</div></div>");$("#bottomSection").html(menu);global.arrow=new global.ArrowClass();global.arrow.createArrow("up");global.arrow.showArrow("none");if(!listing.itemIsVisible()){listingHotKey.index=2;global.rigthNav=listingHotKey;}
if(param.type=="Refine Search"){$("#hotKeyOuter_4").css("width","245px");$("#hotKeyOuter_4").css("background-size","100% 100%");$("#hotKeyOuter_4").css("margin","11px 0 0 1226px");$("#HotKey_4").css("width","245px");$("#label_4").css("width","179px");$("#label_4").css("margin","25px 0 0 0px");}}
listingHotKey.createPageBtn=function(){if((listing.totalListPages>1)&&($("#hotKeyOuter_1").length<=0)){listingHotKey.index=0;var menu="<div id='hotKeyOuter_1'><div class='hotKeys' id='HotKey_1'><div id='redhotKeyImg' class='hotKeyImg' ></div><div id='label_1' class='hotKeyLabel'>Prev Page</div></div></div><div id='hotKeyOuter_2'><div class='hotKeys' id='HotKey_2'><div id='greenhotKeyImg'  class='hotKeyImg'></div><div  id='label_2' class='hotKeyLabel'>Next Page</div></div></div>";$("#hotKeyCont").prepend(menu);}
if($("#hotKeyOuter_1").length>0){if(listing.currentPage==1){$("#label_1").css("color","#c4aa97");$("#redhotKeyImg").css("opacity","0.4");$("#label_2").css("color","white");$("#greenhotKeyImg").css("opacity","1");}else if(listing.currentPage==listing.totalListPages){$("#label_2").css("color","#c4aa97");$("#greenhotKeyImg").css("opacity","0.4");$("#label_1").css("color","white");$("#redhotKeyImg").css("opacity","1");}else{$("#label_1").css("color","white");$("#redhotKeyImg").css("opacity","1");$("#label_2").css("color","white");$("#greenhotKeyImg").css("opacity","1");}}}
listingHotKey.enter_focus=function(){global.focusedDom=this;if(listingHotKey.index==0){$("#HotKey_1").addClass('hotKeyCurser');}else if(listingHotKey.index==1){$("#HotKey_2").addClass('hotKeyCurser');}else{$("#HotKey_4").addClass('hotKeyCurser');}}
listingHotKey.leave_focus=function(){if(listingHotKey.index==0){$("#HotKey_1").removeClass('hotKeyCurser');}else if(listingHotKey.index==1){$("#HotKey_2").removeClass('hotKeyCurser');}else{$("#HotKey_4").removeClass('hotKeyCurser');}}
listingHotKey.KeyboardEvent=function(e,eventType){var target=_target(e),keyCode=target.keyCode,key=global.keyCodeDic[keyCode];switch(eventType){case"keydown":switch(key){case"arrowleft":listingHotKey.leave_focus();if((listingHotKey.index<1)||($("#hotKeyOuter_1").length<=0)){global.mainMenu.enter_focus();}else{listingHotKey.index--;listingHotKey.enter_focus();}
return true;break;case"arrowright":if(listingHotKey.index<2){listingHotKey.leave_focus();listingHotKey.index++;listingHotKey.enter_focus();}
return true;break;case"arrowup":if(listing.itemIsVisible()){listingHotKey.leave_focus();listing.main.enter_focus();return true;}
break;case"ok":$('#downArrow').removeClass("arrowAnim");$('#upArrow').removeClass("arrowAnim");if(listingHotKey.index==2){if(global.gadget==-1){global.clearContents();if(search.SearchAPIData.dataAvailability){search.showSearchScreen({"screen":global.firstSelTab(),"state":"init"})}else{search.createSearch();}}else if(global.gadget==1){global.clearContents();search.createSearch("resetUserReg");}}else if(listingHotKey.index==0){if(listing.currentPage!=1){listingHotKey.leave_focus();listing.currentPage--;listing.main.free();$('#upArrow').addClass("arrowAnim");listing.getListing(listing.currentPage,"hotKey");}}else if(listingHotKey.index==1){if(listing.currentPage!=listing.totalListPages){listingHotKey.leave_focus();listing.currentPage++;listing.currentItem=0;listing.main.free();$('#downArrow').addClass("arrowAnim");listing.getListing(listing.currentPage);}}
return true;break;}
return false;}
return false;};listing.filterCat=function(list,value){var Obj=list.filter(function(list){return list.TypeId==value;});return Obj;}
listing.createHTMl=function(){document.getElementById("innerSection").innerHTML="";var wrapper=document.getElementById("innerSection"),parent=document.createElement('div'),heading=document.createElement('div'),headingtxt=document.createElement('div'),listbg=document.createElement('div'),halalbg=document.createElement('div'),total=0,totalPages=0,itemsReqd=0,maxItems=4;this.data=null;listing.totalListPages=0;this.components=[];heading.id="listingHeading";heading.className="listingHeading";headingtxt.id="listingHeadingTxt";headingtxt.className="listingHeadingTxt";halalbg.id="listHalal"
listbg.id="listingListbg";listbg.className="listingListbg";parent.id="listingBg";parent.className="listingBg";heading.appendChild(headingtxt);heading.appendChild(halalbg);parent.appendChild(heading);parent.appendChild(listbg);wrapper.appendChild(parent);this.listGrid=function(param){try{var bg=document.createElement('div'),cursor=document.createElement('div'),imgbg=document.createElement('div'),loading=document.createElement('p'),img=document.createElement('img'),title=document.createElement('div'),districtbg=document.createElement('div'),district=document.createElement('div'),price=document.createElement('div'),type=document.createElement('div'),smileyBg=document.createElement('div'),happy=document.createElement('img'),happytxt=document.createElement('div'),ok=document.createElement('img'),oktxt=document.createElement('div');imgbg.id="listGridImgBg_"+param.id;imgbg.className="listGridImgBg";loading.id="thumbnailLoading_"+param.id;loading.className="listingThumbnailLoading";loading.innerHTML="Loading...";img.id="listGridimg_"+param.id;img.className="listGridImg fadingAnim";img.src=param.img;function imgLoad(){$("#thumbnailLoading_"+param.id).css("display","none");$("#"+img.id).css("display","block");}
function imgError(){$("#loadingText"+param.id).css("display","none");$("#"+img.id).attr("src","images/detail/default_image.png");}
img.onload=imgLoad;img.onerror=imgError;title.id="listGridTitle_"+param.id;title.className="listGridTitle";title.innerHTML=param.title;districtbg.id="listGridDistrictBg_"+param.id;districtbg.className="listGridDistrictBg";district.id="listGridDistrict_"+param.id;district.className="listGridDistrict";district.innerHTML=param.district;price.id="listGridPrice_"+param.id;price.className="listGridPrice";price.innerHTML=param.price;type.id="listGridType_"+param.id;type.className="listGridType";type.innerHTML=param.type;smileyBg.id="listGridSmileyBg_"+param.id;smileyBg.className="listGridSmileyBg";happy.id="listGridHappy_"+param.id;happy.className="listGridHappy";happy.src="images/detail/happy.png";happytxt.id="listGridHappyTxt_"+param.id;happytxt.className="listGridHappyTxt";happytxt.innerHTML=param.happy;ok.id="listGridOk_"+param.id;ok.className="listGridOk";ok.src="images/detail/ok.png";oktxt.id="listGridOkTxt_"+param.id;oktxt.className="listGridOkTxt";oktxt.innerHTML=param.ok;cursor.className="listGridcursor";cursor.className="listGridcursor";districtbg.appendChild(district);districtbg.appendChild(price);imgbg.appendChild(loading);imgbg.appendChild(img);bg.appendChild(imgbg);bg.appendChild(title);bg.appendChild(districtbg);bg.appendChild(type);bg.appendChild(smileyBg);bg.appendChild(cursor);bg.id="listGridBg_"+param.id;bg.className="listGridBg";if(param.price!=""){district.innerHTML+="<span style='font-weight:900;'> | </span>";}
if(parseInt(param.happy)||parseInt(param.ok)){smileyBg.appendChild(happy);smileyBg.appendChild(happytxt);smileyBg.appendChild(ok);smileyBg.appendChild(oktxt);if(parseInt(param.happy)==parseInt(param.ok)){ok.style.height="64px";ok.style.top="25px";ok.style.right="27px";happy.style.height="64px";happy.style.top="23px";happy.style.left="13px";}else if(parseInt(param.happy)<parseInt(param.ok)){ok.style.height="86px";ok.style.top="0px";ok.style.right="16px";happy.style.height="64px";happy.style.top="16px";happy.style.left="17px";}}
bg.setCursor=function(){cursor.style.display="block";};bg.removeCursor=function(){cursor.style.display="none";};return bg;}catch(e){}};this.setHeading=function(){var headerTxt=listing.getSearchSelectionsName();if(headerTxt!="")
headingtxt.innerHTML="<span style='color:#ffb800;'>Selection Display: </span>"+headerTxt;if(global.checkMYHomeScreen()){halalbg.innerHTML="<span style='float:left;color:#ffb800;'>Halal</span>";}else{$("#listHalal").remove();}};this.setdata=function(param,direction){try{this.data=param||{};var district="";listbg.innerHTML="";this.components=[];if(this.data.Root.Data[0].Pois[0].total&&this.data.Root.Data[0].Pois[0].count){if(parseInt(this.data.Root.Data[0].Pois[0].total)<parseInt(this.data.Root.Data[0].Pois[0].count)){total=parseInt(this.data.Root.Data[0].Pois[0].count)||0;}else{total=parseInt(this.data.Root.Data[0].Pois[0].total)||0;}}else{total=parseInt(this.data.Root.Data[0].Pois[0].total)||0;}
total=(total>250?250:total);if(total==0)
return;totalPages=parseInt(total/maxItems)+((total%maxItems)==0?0:1);listing.totalListPages=totalPages;itemsReqd=(totalPages==listing.currentPage)?(total%maxItems):maxItems;if(0==itemsReqd){itemsReqd=maxItems;}
if(this.data.Root.Data[0].Pois[0].Poi&&(this.data.Root.Data[0].Pois[0].Poi.length>0)){for(var item in this.data.Root.Data[0].Pois[0].Poi){try{if(this.data.Root.Data[0].Pois[0].Poi[item].Districts&&this.data.Root.Data[0].Pois[0].Poi[item].Districts[0]&&this.data.Root.Data[0].Pois[0].Poi[item].Districts[0].District){district=this.data.Root.Data[0].Pois[0].Poi[item].Districts[0].District[0].NameLang1||"N/A";}
var type=[];var value="";if(this.data.Root.Data[0].Pois[0].Poi[item].Categories&&this.data.Root.Data[0].Pois[0].Poi[item].Categories[0]&&this.data.Root.Data[0].Pois[0].Poi[item].Categories[0].Category){type=this.fliter(this.data.Root.Data[0].Pois[0].Poi[item].Categories[0].Category);for(var i in type){value+=type[i];if(i!=type.length-1)
value+="<span style='font-weight:900;'> | </span>";}}
var imgurl=(this.data.Root.Data[0].Pois[0].Poi[item].DoorPhotos&&this.data.Root.Data[0].Pois[0].Poi[item].DoorPhotos[0]&&this.data.Root.Data[0].Pois[0].Poi[item].DoorPhotos[0].DoorPhoto&&this.data.Root.Data[0].Pois[0].Poi[item].DoorPhotos[0].DoorPhoto[0].UrlSmall);listbg.appendChild(this.listGrid({'id':item,'img':(imgurl||detail.errorImgSrc),'title':this.data.Root.Data[0].Pois[0].Poi[item].NameLang1||"N/A",'district':district,'price':(this.data.Root.Data[0].Pois[0].Poi[item].PriceDescription?this.data.Root.Data[0].Pois[0].Poi[item].PriceDescription:""),'type':value,'happy':(this.data.Root.Data[0].Pois[0].Poi[item].ScoreSmile||this.data.Root.Data[0].Pois[0].Poi[item].ScoreSmile!="")?this.data.Root.Data[0].Pois[0].Poi[item].ScoreSmile:0,'ok':(this.data.Root.Data[0].Pois[0].Poi[item].ScoreOK||this.data.Root.Data[0].Pois[0].Poi[item].ScoreOK!="")?this.data.Root.Data[0].Pois[0].Poi[item].ScoreOK:0}));}catch(e){}}
itemsReqd=this.data.Root.Data[0].Pois[0].Poi.length;while(itemsReqd--){id="listGridBg_"+itemsReqd;if(document.getElementById(id)){this.components[itemsReqd]=document.getElementById(id);}};}
if(direction=="up"){listing.currentItem=((this.components.length-1)<0?0:(this.components.length-1));}else if(direction=="hotKey"){listing.currentItem=0;}
this.setArrow();listingHotKey.createPageBtn();global.rigthNav=this;global.mainMenu.leave_focus();if(global.defaultSet){global.defaultSet=false;global.defaultSetpopUp.create("defaultSet",this);}else{this.enter_focus();}
if(totalPages>1){this.createPage();}}catch(e){}};this.createPage=function(){if($("#listingPage").length>0){$("#listingPage").remove();}
outer="<div id='listingPage'>"+listing.currentPage+" of "+totalPages+"</div>";$("#innerSection").append(outer);}
this.fliter=function(list){var list=list||[]
var id=[1,2,3,4];var cuisineObj=[];for(var i=0;i<id.length;i++){for(var a in list){if(list[a].TypeId==id[i]){cuisineObj.push(list[a].NameLang1);break;}}}
return cuisineObj;};this.enter_focus=function(){try{global.focusedDom=this;this.components[listing.currentItem].setCursor();}catch(e){}};this.leave_focus=function(){this.components[listing.currentItem].removeCursor();};this.free=function(){listbg.innerHTML="";this.components=[];};this.setArrow=function(){try{if(totalPages==1){return;}
if(listing.currentPage==1){global.arrow.showArrow("down");}else if(listing.currentPage>1&&listing.currentPage<totalPages){global.arrow.showArrow("both");}else if(listing.currentPage==totalPages){global.arrow.showArrow("up");}}catch(e){}}
this.KeyboardEvent=function(e,eventType){try{var target=_target(e),keyCode=target.keyCode,key=global.keyCodeDic[keyCode];$('#downArrow').removeClass("arrowAnim");$('#upArrow').removeClass("arrowAnim");switch(eventType){case"keydown":switch(key){case"arrowup":if(this.components[listing.currentItem-1]){this.components[listing.currentItem].removeCursor();this.components[--listing.currentItem].setCursor();}else{if(listing.currentPage!=1){listing.currentPage--;this.free();$('#upArrow').addClass("arrowAnim");listing.getListing(listing.currentPage,"up");}}
return true;break;case"arrowdown":if(this.components[listing.currentItem+1]){this.components[listing.currentItem].removeCursor();this.components[++listing.currentItem].setCursor();return true;}else{if(listing.currentPage!=totalPages){listing.currentPage++;listing.currentItem=0;this.free();$('#downArrow').addClass("arrowAnim");listing.getListing(listing.currentPage);return true;}else{this.components[listing.currentItem].removeCursor();listingHotKey.enter_focus();}}
return true;case"ok":listing.selectedItem=this.data.Root.Data[0].Pois[0].Poi[listing.currentItem].Id;this.free();detail.createDetail("default");try{detail.main.reset();}catch(e){}
break;case"arrowleft":this.leave_focus();global.mainMenu.enter_focus();return true;break;}
return false;}
return false;}catch(e){}};};listing.getListing=function(page,direction){var page=page||1;var URL=listing.createUrl(page);if(!URL){return false;}
try{if($("#errorContent").length>0){$("#errorContent").remove();}
global.loading.On();$.ajax({type:"GET",url:URL,headers:{'or-token':global.OR_Token,},dataType:"json",timeout:30000,success:function(data){try{global.splash.Off();global.loading.Off();var feedValue=data;if(feedValue!=null&&feedValue.Root&&feedValue.Root.Data[0]){if(feedValue.Root.Data[0].Errors&&feedValue.Root.Data[0].Errors[0]&&feedValue.Root.Data[0].Errors[0].Error){if(global.screen==1){search.showSearchListError.create("listing");}else{global.showError("listing","dontClearBtm","inList");}}else{if(feedValue.Root.Data[0].Pois&&feedValue.Root.Data[0].Pois[0]&&feedValue.Root.Data[0].Pois[0].Poi){if(global.screen==1){global.screen=2;global.clearContents();listing.main=new listing.createHTMl();global.mainMenu.makeSelected(0);global.mainMenu.enter_focus();global.removeHotKey("up");if(global.gadget==1){listingHotKey.create({"type":"Search"});}else{listingHotKey.create({"type":"Refine Search"});}}
global.mainMenu.leave_focus();global.mainMenu.makeSelected(0);listing.main.setHeading();listing.main.setdata(feedValue,direction);}else{if(global.screen==1){search.showSearchListError.create("listing");}else{global.showError("listing","dontClearBtm","inList");}}}}else{if(global.screen==1){search.showSearchListError.create("listing");}else{global.showError("listing","dontClearBtm","inList");}}}catch(e){if(global.screen==1){search.showSearchListError.create("listing");}else{global.showError("listing","dontClearBtm","inList");}}},error:function(jqXHR,textStatus,errorThrown){global.splash.Off();global.loading.Off();if(global.screen==1){search.showSearchListError.create("network");}else{global.showError("network","dontClearBtm","inList");}}});}catch(e){global.splash.Off();global.loading.Off();if(global.screen==1){search.showSearchListError.create("listing");}else{global.showError("listing","dontClearBtm","inList");}}}