// Copyright (C) 2014 Open Rice & Panasonic Corporation. All Rights Reserved.
//
//****************************/
// File Name: search.js
// Purpose: This document creates search criteria page with async true API.
// File Created Date: 17-Oct-2013
// Release Date: 02-Jan-2014
// Release Version: 1.4
//****************************/
var search={"menu":["District","Cuisine","Dish","Restaurant Type","Theme","Price"],"select":["Select District: ","Select Cuisine: ","Select Dish Type: ","Select Restaurant Type: ","Select Theme: ","Select Price: "],"curMenu":0,"curFocusMenu":0,"maxLimitTimerObj":{},"row_col":{},"menusWithSelection":[]};search.Selections={"region":{"country":"","city_Id":[],"city_Name":[],"headerSelected":{}},"district":{"noOfSelection":0,"id":{},"name":{},"headerSelected":{}},"cuisine":{"noOfSelection":0,"id":{},"name":{},"headerSelected":{},"headerWithGroupSel":{}},"dish":{"id":[],"name":[]},"restaurantType":{"id":[],"name":[]},"theme":{"id":"","name":""},"price":{"id":"","name":""},};search.SearchAPIData={"dataAvailability":false,"district":{"districtGroup":[],"districtGroupList":[],},"cuisine":{"cuisineGroup":[],"cuisineGroupList":[],},"dish":{"id":[2],"name":["v"],},"restaurantType":{"id":[2],"name":["v"],},"theme":{"id":[2],"name":["v"],},"price":{"id":[2],"name":["v"],},};search.getSelections=function(param){if(param.category&&param.type)
return search.Selections[param.category][param.type];}
search.filterDisGroup=function(value){if(value.GroupDistrictId==value.Id){return true;}}
search.filterCatGroup=function(value){if(value.CategoryGroupId==value.Id){return true;}}
search.filterGroupList=function(arr,criteria,checkTagName){return arr.filter(function(obj){return Object.keys(criteria).every(function(c){if(obj[c]==criteria[c]){return obj[c]!=obj[checkTagName]}});});}
search.getAPIDistrict=function(param){var feedValue=param
search.SearchAPIData.district.districtGroup=feedValue.filter(search.filterDisGroup);search.SearchAPIData.district.districtGroupList=[];for(var loop=0;loop<search.SearchAPIData.district.districtGroup.length;loop++){var groupArr=search.filterGroupList(feedValue,{GroupDistrictId:search.SearchAPIData.district.districtGroup[loop].GroupDistrictId},"Id");var idArr=[];var nameArr=[];idArr=groupArr.map(function(val){return val.Id;});nameArr=groupArr.map(function(val){return val.NameLang1;});search.SearchAPIData.district.districtGroupList.push({"districtId":idArr,"districtName":nameArr});}}
search.getAPICategories=function(list){try{var cuisineObj=list.filter(function(list){return list.CategoryTypeId=="1";});search.SearchAPIData.cuisine.cuisineGroup=cuisineObj.filter(search.filterCatGroup);search.SearchAPIData.cuisine.cuisineGroupList=[];for(var loop=0;loop<search.SearchAPIData.cuisine.cuisineGroup.length;loop++){var groupArr=search.filterGroupList(list,{CategoryGroupId:search.SearchAPIData.cuisine.cuisineGroup[loop].CategoryGroupId},"Id");var idArr=[];var nameArr=[];idArr=groupArr.map(function(val){return val.Id;});nameArr=groupArr.map(function(val){return val.NameLang1;});idArr.unshift(search.SearchAPIData.cuisine.cuisineGroup[loop].CategoryGroupId);nameArr.unshift("Select All");search.SearchAPIData.cuisine.cuisineGroupList.push({"cuisineId":idArr,"cuisineName":nameArr});}
search.fillData(list);}catch(e){}}
search.fillData=function(list){var dishObj=list.filter(function(list){return list.CategoryTypeId=="2";});search.SearchAPIData.dish.id=[];search.SearchAPIData.dish.name=[];search.SearchAPIData.restaurantType.id=[];search.SearchAPIData.restaurantType.name=[];search.SearchAPIData.theme.id=[];search.SearchAPIData.theme.name=[];for(var loop=0;loop<dishObj.length;loop++){search.SearchAPIData.dish.id[loop]=dishObj[loop].Id;search.SearchAPIData.dish.name[loop]=dishObj[loop].NameLang1;}
dishObj=list.filter(function(list){return list.CategoryTypeId=="3";});for(var loop=0;loop<dishObj.length;loop++){search.SearchAPIData.restaurantType.id[loop]=dishObj[loop].Id;search.SearchAPIData.restaurantType.name[loop]=dishObj[loop].NameLang1;}
dishObj=list.filter(function(list){return list.CategoryTypeId=="4";});for(var loop=0;loop<dishObj.length;loop++){search.SearchAPIData.theme.id[loop]=dishObj[loop].Id;search.SearchAPIData.theme.name[loop]=dishObj[loop].NameLang1;}}
search.fillPriceData=function(list){search.SearchAPIData.price.id=[];search.SearchAPIData.price.name=[];for(var loop=0;loop<list.length;loop++){search.SearchAPIData.price.id[loop]=list[loop].PriceRangeId;search.SearchAPIData.price.name[loop]=list[loop].NameLang1;}}
search.clearAllScreen=function(){for(var loop=2;loop<6;loop++){search.menuGridContainer.clearAll(loop);}
search.deSelectAll_Distirct();search.deSelectAll_Cuisine();search.menusWithSelection[0]=false;search.menusWithSelection[1]=false;$("#star_0").css("visibility","hidden");$("#star_1").css("visibility","hidden");$("#label_3").css("color","#c4aa97");$("#yellowhotKeyImg").css("opacity","0.4");$("#selectType").css("display","none");if((search.curMenu==0||search.curMenu==1)&&(global.focusedDom===region.clear)){region.clear.leave_focus();region.set_focus();}}
search.getSearchCriteria=function(param){try{global.clearContents();search.SearchAPIData.dataAvailability=false;global.screen=1;global.gadget=-1;global.rigthNav=null;global.loading.On();$.ajax({type:"GET",url:param.url,headers:{'or-token':global.OR_Token,},dataType:"json",timeout:30000,success:function(data){try{global.splash.Off();global.loading.Off();var feedValue=data;global.screen=1;if(feedValue!=null&&feedValue.Root&&feedValue.Root.Data[0]){if(feedValue.Root.Data[0].Errors){global.showError("search","clearBottom");global.mainMenu.makeSelected(0);global.mainMenu.enter_focus();}else{search.SearchAPIData.dataAvailability=true;if(feedValue.Root.Data[0].Districts&&feedValue.Root.Data[0].Districts[0]&&feedValue.Root.Data[0].Districts[0].District){search.getAPIDistrict(feedValue.Root.Data[0].Districts[0].District);}
if(feedValue.Root.Data[0].Categories&&feedValue.Root.Data[0].Categories[0]&&feedValue.Root.Data[0].Categories[0].Category){search.getAPICategories(feedValue.Root.Data[0].Categories[0].Category);}
if(feedValue.Root.Data[0].PriceRanges&&feedValue.Root.Data[0].PriceRanges[0]&&feedValue.Root.Data[0].PriceRanges[0].PriceRange){search.fillPriceData(feedValue.Root.Data[0].PriceRanges[0].PriceRange);}
search.showSearchScreen({"screen":search.curMenu,"state":"init","resetAll":"1"});}}else{global.showError("search","clearBottom");global.mainMenu.makeSelected(0);global.mainMenu.enter_focus();}}catch(e){global.showError("search","clearBottom");global.mainMenu.makeSelected(0);global.mainMenu.enter_focus();}},error:function(jqXHR,textStatus,errorThrown){global.splash.Off();global.loading.Off();global.showError("network","clearBottom");global.mainMenu.makeSelected(0);global.mainMenu.enter_focus();}});}catch(e){global.splash.Off();global.loading.Off();global.showError("search","clearBottom");global.mainMenu.makeSelected(0);global.mainMenu.enter_focus();}}
search.createSearch=function(param){var param=param||"";if(param=="resetUserReg"){var ret=global.checkCookie("setCurrentLoc");}
global.urlParams['hscountry']="";var url=global.getServer(search.getSelections({"category":"region","type":"country"}))+"/api/api.htm?method=or.code.getall&region_id="+search.getSelections({"category":"region","type":"city_Id"})+"&api_token=apitoken&api_sig=apisignature&app_type=orpanasonic&response_type=json";search.curMenu=0;search.getSearchCriteria({"url":url});}
search.showSearchScreen=function(param){try{global.screen=1;global.gadget=-1;hotKeyObj.hotKeyCur=1;region.accordionScreen="district";search.curMenu=param.screen;global.rigthNav=null;global.mainMenu.leave_focus();switch(param.screen){case 0:search.createDistrict(param);break;case 1:search.createCuisine(param);break;case 2:case 3:search.menuGridContainer.freeAll();search.menuGridContainer.createGrid_dishRestaurant(param);break;case 4:case 5:search.menuGridContainer.freeAll();search.menuGridContainer.createGrid(param);break;}
if(search.curMenu==0){$("#label_1").text("Last Menu");$("#label_2").text("Next Menu");}else if(search.curMenu==5){$("#label_2").text("First Menu");$("#label_1").text("Prev Menu");}else{$("#label_1").text("Prev Menu");$("#label_2").text("Next Menu");}
search.menuGridContainer.show_hide_patch(param.screen);}catch(e){}}
search.freeContent=function(){if(document.getElementById("errorContent"))
$("#errorContent").remove();if(document.getElementById("content"))
$("#content").remove();}
search.createDistrict=function(param){try{var param=param||"";if(param.resetAll&&param.resetAll=="1"){if($("#regionPopUp").length>0){clearTimeout(search.maxLimitTimerObj);region.popUpHide();}
for(var i=0;i<search.menusWithSelection.length;i++){search.menusWithSelection[i]=false;}
search.Selections.district.noOfSelection=0;search.Selections.cuisine.noOfSelection=0;search.Selections.cuisine.headerWithGroupSel={};search.Selections.district.headerSelected={};search.Selections.cuisine.headerSelected={};search.Selections.district.id={};search.Selections.district.name={};search.Selections.cuisine.id={};search.Selections.cuisine.name={};search.Selections.dish.id=[];search.Selections.dish.name=[];search.Selections.restaurantType.id=[];search.Selections.restaurantType.name=[];search.Selections.theme.id="";search.Selections.theme.name="";search.Selections.price.id="";search.Selections.price.name="";}
global.removeHotKey("up");if(search.SearchAPIData.district.districtGroup.length<=0&&search.SearchAPIData.cuisine.cuisineGroup.length<=0&&search.SearchAPIData.dish.id.length<=0&&search.SearchAPIData.restaurantType.id.length<=0&&search.SearchAPIData.theme.id.length<=0&&search.SearchAPIData.price.id.length<=0){global.clearContents();global.showError("search","clearBottom");global.mainMenu.makeSelected(0);global.mainMenu.enter_focus();}else{if(param.state&&param.state=="init"){global.clearContents();global.mainMenu.makeSelected(0);search.searchMenuContainer.createMenu(param.screen);global.mainMenu.leave_focus();global.focusedDom=search;}
search.freeContent();global.createHotKey();if(search.SearchAPIData.district.districtGroup.length==0){global.showError("district","dontClearBtm");search.curMenu=0;search.searchMenuContainer.enter_focus(search.curMenu);}else{global.createContents("search");region.accordion=document.getElementById("accordion");region.accordionScreen="district";var index=0;var feed="";region.header_index=0;region.panel_index=0;for(var k in search.SearchAPIData.district.districtGroup){try{feed+=region.createAccordion({"index":index,"headerName":search.SearchAPIData.district.districtGroup[k].NameLang1,"headerId":search.SearchAPIData.district.districtGroup[k].GroupDistrictId,"error":"districts","data":{"Id":search.SearchAPIData.district.districtGroupList[k].districtId,"Name":search.SearchAPIData.district.districtGroupList[k].districtName}});index++;}catch(e){}}
region.noOfAcc=index;region.accordion.innerHTML=feed;region.setAccordion();region.createArrow(region.header_index);region.arr();if(search.Selections.district.noOfSelection>0){$("#selectType").css("display","block");}else{$("#selectType").css("display","none");}}
search.searchMenuContainer.checkForEmptySearch();}}catch(e){}}
search.createCuisine=function(param){try{var param=param||"";if(param.state&&param.state=="init"){global.clearContents();global.mainMenu.makeSelected(0);search.searchMenuContainer.createMenu(param.screen);global.mainMenu.leave_focus();global.focusedDom=search;}
search.freeContent();global.createHotKey();if(search.SearchAPIData.cuisine.cuisineGroup.length==0){global.showError("cuisine","dontClearBtm");search.curMenu=1;search.searchMenuContainer.enter_focus(search.curMenu);}else{global.createContents("search");region.accordion=document.getElementById("accordion");region.accordionScreen="cuisine";var index=0;var feed="";region.header_index=0;region.panel_index=0;for(var k in search.SearchAPIData.cuisine.cuisineGroup){try{feed+=region.createAccordion({"index":index,"headerName":search.SearchAPIData.cuisine.cuisineGroup[k].NameLang1,"headerId":search.SearchAPIData.cuisine.cuisineGroup[k].CategoryGroupId,"error":"cuisines","data":{"Id":search.SearchAPIData.cuisine.cuisineGroupList[k].cuisineId,"Name":search.SearchAPIData.cuisine.cuisineGroupList[k].cuisineName}});index++;}catch(e){}}
region.noOfAcc=index;region.accordion.innerHTML=feed;region.setAccordion();region.createArrow(region.header_index);region.arr();global.focusedDom=search;if(search.Selections.cuisine.noOfSelection>0){$("#selectType").css("display","block");}else{$("#selectType").css("display","none");}
search.searchMenuContainer.checkForEmptySearch();}}catch(e){}}
search.filterId=function(arr,checkValue){return arr.filter(function(obj){if(obj==checkValue)
return true;else
return false;});}
search.showSearchListError=(function(){var obj={};var prevCursor="";obj.create=function(param){prevCursor=global.focusedDom;obj.show();var idVal="searchListErrorIcon";if(param=="defaultSearch"){idVal="searchListInfoIcon";}
if($("#fullMask").length>0){$("#fullMask").remove();}
if($("#searchListError").length>0){$("#searchListError").remove();}
var fullMask="<div id = 'fullMask' class = 'fullMaskCls'></div>";var outer="<div id='searchListError'><div id="+idVal+"></div><div id ='searchListErrorText'>"+global.getError(param)+"</div><div id='searchListError_Ok' class = 'normal'><div id='searchListError_OkInner'>OK</div></div></div>";$("#wrapper").append(fullMask);$("#wrapper").append(outer);obj.enter_focus("searchListError_Ok");}
obj.enter_focus=function(id){global.focusedDom=this;$("#"+id).attr("class","change");$("#"+id+"Inner").addClass("exitCurser");}
obj.leave_focus=function(id){$("#"+id).attr("class","normal");$("#"+id+"Inner").removeClass("exitCurser");}
obj.show=function(){switch(prevCursor){case search.searchMenuContainer:if($("#clearAll").hasClass('clearCursor')){prevCursor.leave_focus_clear();}else{prevCursor.leave_focus(search.curFocusMenu);}
break;case search.menuGridContainer:if($("#price").hasClass("priceCursor")){search.row_col.leftRetVal="price";search.menuGridContainer.leave_focus_price();}else{prevCursor.leave_focus(search.row_col.row,search.row_col.col);}
break;case search:prevCursor=region;default:if(typeof prevCursor==='object'&&prevCursor.leave_focus)
prevCursor.leave_focus();break;}}
obj.hide=function(){$("#searchListError").remove();$("#fullMask").remove();switch(prevCursor){case search.searchMenuContainer:prevCursor.enter_focus(search.curFocusMenu);break;case search.menuGridContainer:if(search.row_col.leftRetVal=="grid"){prevCursor.enter_focus();}else{search.menuGridContainer.enter_focus_price();}
break;case search:prevCursor=region;default:prevCursor.enter_focus();break;}}
obj.KeyboardEvent=function(e,eventType){var target=_target(e),keyCode=target.keyCode,key=global.keyCodeDic[keyCode];switch(eventType){case"keydown":switch(key){case"ok":obj.hide();return true;break;case"return":e.preventDefault();obj.hide();return true;break;}
break;}};return obj;})();search.showSelected=function(arrlist,checkValue,index){var keyValue="header_"+index+"_"+region.header_page["header_"+index];if((!isEmptyList(arrlist.id))&&(arrlist.id[keyValue])){if(search.filterId(arrlist.id[keyValue],checkValue)!="")
return true;}
return false;}
search.selectAll_CuisineAction=function(type){try{var type=type||"";var index=region.activeAccordion;var idList=search.SearchAPIData.cuisine.cuisineGroupList[index].cuisineId;var startIndex=1;var endIndex=(region.header_page["header_"+index]*region.maxRows*region.maxCols);var cls=((type=="select")?"panelDis-disable":"districtItem");for(var loopVar=startIndex;loopVar<(endIndex>idList.length?idList.length:endIndex);loopVar++){if(document.getElementById("panelCur_"+index+"_"+loopVar)){document.getElementById("panelCur_"+index+"_"+loopVar).className=cls;}}}catch(e){}}
search.selectItem=function(arrlist){try{var idValue=$('#panel_'+region.activeAccordion+"_"+region.panel_index).attr("data-mydata").toString();var nameValue=$('#panel_'+region.activeAccordion+"_"+region.panel_index).text().toString();var keyValue="header_"+region.activeAccordion+"_"+region.header_page["header_"+region.activeAccordion];if(region.accordionScreen=="cuisine"){if(nameValue=="Select All"){if((arrlist.headerSelected["header_"+region.activeAccordion]!=='undefined')&&(arrlist.headerSelected["header_"+region.activeAccordion])){arrlist.noOfSelection-=arrlist.headerSelected["header_"+region.activeAccordion];}}}
if(arrlist.noOfSelection==5){if($("#maxLimitPopUp").length==0){search.menuGridContainer.popUpCreate();}
return false;}
if(region.accordionScreen=="cuisine"){if(nameValue=="Select All"){arrlist.headerWithGroupSel["header_"+region.activeAccordion]=true;nameValue=$("#header_"+region.activeAccordion).text().toString();if((arrlist.headerSelected["header_"+region.activeAccordion]!=='undefined')&&(arrlist.headerSelected["header_"+region.activeAccordion])){for(var key in arrlist.id){if(key.substring(0,("header_"+region.activeAccordion+"_").length)==("header_"+region.activeAccordion+"_")){arrlist.id[key]=[];arrlist.name[key]=[];}}
if(arrlist.noOfSelection<0)
arrlist.noOfSelection=0;}
search.selectAll_CuisineAction("select");}}
if(!arrlist.id[keyValue]){arrlist.noOfSelection++;arrlist.id[keyValue]=[idValue];arrlist.name[keyValue]=[nameValue];document.getElementById("panelCur_"+region.activeAccordion+"_"+region.panel_index).className="panelDis-selected";region.clear.show();$('#regionHeader_selectedNo').text(arrlist.noOfSelection.toString());}else{var indexValue=arrlist.id[keyValue].indexOf(idValue);if(indexValue<0){arrlist.noOfSelection++;arrlist.id[keyValue].push(idValue);arrlist.name[keyValue].push(nameValue);document.getElementById("panelCur_"+region.activeAccordion+"_"+region.panel_index).className="panelDis-selected";region.clear.show();$('#regionHeader_selectedNo').text(arrlist.noOfSelection.toString());}}
if(!arrlist.headerSelected["header_"+region.activeAccordion]){arrlist.headerSelected["header_"+region.activeAccordion]=0;}
if(arrlist.noOfSelection>0){$("#selectType").css("display","block");$("#star_"+search.curMenu).css("visibility","visible");arrlist.headerSelected["header_"+region.activeAccordion]+=1;if(!$("#headerStar_"+region.activeAccordion).hasClass("headerStarCls"))
$("#headerStar_"+region.activeAccordion).addClass("headerStarCls");search.menusWithSelection[search.curMenu]=true;}else{$("#selectType").css("display","none");search.menusWithSelection[search.curMenu]=false;$("#star_"+search.curMenu).css("visibility","hidden");}
search.searchMenuContainer.checkForEmptySearch();}catch(e){}}
search.deSelectItem=function(arrlist){try{var idValue=$('#panel_'+region.activeAccordion+"_"+region.panel_index).attr("data-mydata").toString();var keyValue="header_"+region.activeAccordion+"_"+region.header_page["header_"+region.activeAccordion];var indexValue=arrlist.id[keyValue].indexOf(idValue);if(region.accordionScreen=="cuisine"){var nameValue=$('#panel_'+region.activeAccordion+"_"+region.panel_index).text().toString();if(nameValue=="Select All"){arrlist.headerWithGroupSel["header_"+region.activeAccordion]=false;arrlist.headerSelected["header_"+region.activeAccordion]=1;search.selectAll_CuisineAction("deselect");}}
if(indexValue>-1){arrlist.noOfSelection--;arrlist.id[keyValue].splice(indexValue,1);arrlist.name[keyValue].splice(indexValue,1);document.getElementById("panelCur_"+region.activeAccordion+"_"+region.panel_index).className="districtItem";if(arrlist.noOfSelection>0){region.clear.show();$('#regionHeader_selectedNo').text(arrlist.noOfSelection.toString());}else{region.clear.remove();$('#regionHeader_selectedNo').text("");}}
if(arrlist.noOfSelection>0){$("#selectType").css("display","block");search.menusWithSelection[search.curMenu]=true;$("#star_"+search.curMenu).css("visibility","visible");}else{$("#star_"+search.curMenu).css("visibility","hidden");search.menusWithSelection[search.curMenu]=false;$("#selectType").css("display","none");}
arrlist.headerSelected["header_"+region.activeAccordion]-=1;if(arrlist.headerSelected["header_"+region.activeAccordion]==0){arrlist.headerSelected["header_"+region.activeAccordion]=false;$("#headerStar_"+region.activeAccordion).removeClass("headerStarCls");}
search.searchMenuContainer.checkForEmptySearch();}catch(e){}}
search.deSelectAll_Distirct=function(){try{var index=0;for(var k in search.SearchAPIData.district.districtGroupList){var idList=search.SearchAPIData.district.districtGroupList[k].districtId;var startIndex=(region.header_page["header_"+index]==1?0:((region.header_page["header_"+index]*region.maxRows*region.maxCols)-(region.maxRows*region.maxCols)));var endIndex=(region.header_page["header_"+index]*region.maxRows*region.maxCols);for(var loopVar=startIndex;loopVar<(endIndex>idList.length?idList.length:endIndex);loopVar++){if(document.getElementById("panelCur_"+index+"_"+loopVar)){document.getElementById("panelCur_"+index+"_"+loopVar).className="districtItem";}}
if(document.getElementById("headerStar_"+index)){document.getElementById("headerStar_"+index).className="";}
index++;}
search.Selections.district.noOfSelection=0;search.Selections.district.headerSelected={};search.Selections.district.id={};search.Selections.district.name={};region.clear.remove();$("#star_"+search.curMenu).css("visibility","hidden");search.menusWithSelection[search.curMenu]=false;$('#regionHeader_selectedNo').text("");search.searchMenuContainer.checkForEmptySearch();$("#selectType").css("display","none");}catch(e){}}
search.deSelectAll_Cuisine=function(){try{var index=0;for(var k in search.SearchAPIData.cuisine.cuisineGroupList){var idList=search.SearchAPIData.cuisine.cuisineGroupList[k].cuisineId;var startIndex=(region.header_page["header_"+index]==1?0:((region.header_page["header_"+index]*region.maxRows*region.maxCols)-(region.maxRows*region.maxCols)));var endIndex=(region.header_page["header_"+index]*region.maxRows*region.maxCols);for(var loopVar=startIndex;loopVar<(endIndex>idList.length?idList.length:endIndex);loopVar++){if(document.getElementById("panelCur_"+index+"_"+loopVar)){document.getElementById("panelCur_"+index+"_"+loopVar).className="districtItem";}}
if(document.getElementById("headerStar_"+index)){document.getElementById("headerStar_"+index).className="";}
index++;}
search.Selections.cuisine.headerWithGroupSel={};search.Selections.cuisine.noOfSelection=0;search.Selections.cuisine.headerSelected={};search.Selections.cuisine.id={};search.Selections.cuisine.name={};region.clear.remove();$("#star_"+search.curMenu).css("visibility","hidden");search.menusWithSelection[search.curMenu]=false;$('#regionHeader_selectedNo').text("");search.searchMenuContainer.checkForEmptySearch();$("#selectType").css("display","none");}catch(e){}}
search.KeyboardEvent=function(e,eventType){try{var target=_target(e),keyCode=target.keyCode,key=global.keyCodeDic[keyCode];region.activeAccordion=$("#accordion").accordion("option","active");if(global.loadOn){e.preventDefault();return true;}
switch(eventType){case"keydown":switch(key){case"arrowdown":region.downKey();return true;break;case"arrowup":region.upKey();return true;break;case"ok":if($('#header_'+region.header_index).hasClass("header-cursor")){if(region.noOfAcc>1){((region.activeAccordion===region.header_index)?(function(){$("#accordion").accordion({active:false});region.arr();})():(function(){$("#accordion").accordion({active:region.header_index});region.arr();})());}}else{var listArray="";var selectAll=false;if(region.accordionScreen=="district"){listArray=search.Selections.district;}else if(region.accordionScreen=="cuisine"){listArray=search.Selections.cuisine;if((typeof listArray.headerWithGroupSel["header_"+region.activeAccordion]!=='undefined')&&(listArray.headerWithGroupSel["header_"+region.activeAccordion])){selectAll=true;}}
if($('#panelCur_'+region.activeAccordion+"_"+region.panel_index).hasClass("districtItem")){search.selectItem(listArray);}else{if(selectAll){if(region.panel_index==0){search.deSelectItem(listArray);}}else{search.deSelectItem(listArray);}}}
return true;break;case"arrowleft":if($('#header_'+region.header_index).hasClass("header-cursor")){region.leave_focus("header");global.mainMenu.enter_focus();}else{var index=((region.panel_index%region.maxCols)>0?(region.panel_index-1):-1);if(document.getElementById('panel_'+region.activeAccordion+"_"+(index))&&(index>-1)){region.leave_focus("panel");region.panel_index=index;region.enter_focus("panel");}else{if(region.accordionScreen=="district")
region.createPanelData({"index":region.activeAccordion,"dir":"left","Id":search.SearchAPIData.district.districtGroupList[region.activeAccordion].districtId,"Name":search.SearchAPIData.district.districtGroupList[region.activeAccordion].districtName});else if(region.accordionScreen=="cuisine")
region.createPanelData({"index":region.activeAccordion,"dir":"left","Id":search.SearchAPIData.cuisine.cuisineGroupList[region.activeAccordion].cuisineId,"Name":search.SearchAPIData.cuisine.cuisineGroupList[region.activeAccordion].cuisineName});}}
return true;break;case"arrowright":if($('#header_'+region.header_index).hasClass("header-cursor")){}
else{var index=((region.panel_index%region.maxCols)!=(region.maxCols-1)?(region.panel_index+1):-1);if(document.getElementById('panel_'+region.activeAccordion+"_"+(index))&&(index>-1)){region.leave_focus("panel");region.panel_index=index;region.enter_focus("panel");}else{if(region.accordionScreen=="district")
region.createPanelData({"index":region.activeAccordion,"dir":"right","Id":search.SearchAPIData.district.districtGroupList[region.activeAccordion].districtId,"Name":search.SearchAPIData.district.districtGroupList[region.activeAccordion].districtName});else if(region.accordionScreen=="cuisine")
region.createPanelData({"index":region.activeAccordion,"dir":"right","Id":search.SearchAPIData.cuisine.cuisineGroupList[region.activeAccordion].cuisineId,"Name":search.SearchAPIData.cuisine.cuisineGroupList[region.activeAccordion].cuisineName});}}
return true;break;}
return false;}
return false;}catch(e){}};search.menuGridContainer=(function(){var obj={};var row=0,column=0,counter=0,totalRows=0;var page=1,totalPages=0;var selected="",previous="";var index=0;this.leftRetVal="grid";obj.show_hide_patch=function(param){if(param>=2){$("#arrows").css("display","none");if($("#bottomMask").length==0){var top="<div id='bottomMask'></div>";$("#bottomSection").append(top);}}else{$("#arrows").css("display","block");$("#bottomMask").remove();}}
obj.createGrid_dishRestaurant=function(param){var param=param||"";if(param.state&&param.state=="init"){global.clearContents();global.mainMenu.makeSelected(0);search.searchMenuContainer.createMenu(param.screen);global.mainMenu.leave_focus();global.focusedDom=search;}
search.freeContent();if(search.SearchAPIData.dish.id.length==0&&(search.curMenu==2)){global.showError("dish","dontClearBtm");search.searchMenuContainer.enter_focus(search.curMenu);return false;}else if(search.SearchAPIData.restaurantType.id.length==0&&(search.curMenu==3)){global.showError("restaurant","dontClearBtm");search.searchMenuContainer.enter_focus(search.curMenu);return false;}
obj.free();obj.createPrice();$("#selectType").css("display","block");$("#numberVal").css("visibility","visible");var grid="<div id='leftArrowCont'><div id='leftArr'></div></div><div id='gridCentre'></div><div id='rightArrowCont'><div id='rightArr'></div></div>";$("#thumbnail").append(grid);grid="";if(search.curMenu==3){totalPages=parseInt(search.SearchAPIData.restaurantType.name.length/18);if(search.SearchAPIData.restaurantType.name.length%18!=0){totalPages++;}
obj.createPage();if(totalPages<=1){$("#searchPage").css("display","none");}
$("#selectMenu").text(search.select[search.curMenu]);$("#price").text("Restaurant Type");$("#numberVal").text(search.Selections.restaurantType.name.length);if(search.SearchAPIData.restaurantType.name.length<=18){$("#rightArr").css("visibility","hidden");$("#leftArr").css("visibility","hidden");}
if(search.SearchAPIData.restaurantType.name.length<3){totalRows=search.SearchAPIData.restaurantType.name.length}else{totalRows=search.SearchAPIData.restaurantType.name.length/3;}
if(search.SearchAPIData.restaurantType.name.length%3!=0){totalRows++;}
if(totalRows>6){row=6;}else{row=parseInt(totalRows);}
for(var loopVar=0;loopVar<row;loopVar++){for(var loop=0;loop<3;loop++){if(counter==search.SearchAPIData.restaurantType.name.length){break;}
grid="<div class='curser' id='cursor_"+loopVar+"_"+loop+"'><div id='grid_"+loopVar+"_"+loop+"' class='gridDishRestaurant fontstyleDishRestaurant'><div class='divText' id='text_"+loopVar+"_"+loop+"'>"+search.SearchAPIData.restaurantType.name[counter]+"</div></div></div>";$("#gridCentre").append(grid);for(var loopVal=0;loopVal<search.Selections.restaurantType.name.length;loopVal++){if(search.Selections.restaurantType.name[loopVal]==search.SearchAPIData.restaurantType.name[counter]){selected="cursor_"+loopVar+"_"+loop;if(search.Selections.restaurantType.name!=""){$("#"+selected).addClass("selectedDishREst");}}}
counter++;}}
if(search.Selections.restaurantType.name.length>0){$("#selectType").css("display","block");}else{$("#selectType").css("display","none");}}else{totalPages=parseInt(search.SearchAPIData.dish.name.length/18);if(search.SearchAPIData.dish.name.length%18!=0){totalPages++;}
obj.createPage();if(totalPages<=1){$("#searchPage").css("display","none");}
$("#selectMenu").text(search.select[search.curMenu]);$("#price").text("Dish Type");$("#numberVal").text(search.Selections.dish.name.length);if(search.SearchAPIData.dish.name.length<=18){$("#rightArr").css("visibility","hidden");$("#leftArr").css("visibility","hidden");}
if(search.SearchAPIData.dish.name.length<3){totalRows=search.SearchAPIData.dish.name.length}else{totalRows=search.SearchAPIData.dish.name.length/3;}
if(search.SearchAPIData.dish.name.length%3!=0){totalRows++;}
if(totalRows>6){row=6;}else{row=parseInt(totalRows);}
for(var loopVar=0;loopVar<row;loopVar++){for(var loop=0;loop<3;loop++){if(counter==search.SearchAPIData.dish.name.length){break;}
grid="<div class='curser' id='cursor_"+loopVar+"_"+loop+"'><div id='grid_"+loopVar+"_"+loop+"' class='gridDishRestaurant fontstyleDishRestaurant'><div class='divText' id='text_"+loopVar+"_"+loop+"'>"+search.SearchAPIData.dish.name[counter]+"</div></div></div>";$("#gridCentre").append(grid);for(var loopVal=0;loopVal<search.Selections.dish.name.length;loopVal++){if(search.Selections.dish.name[loopVal]==search.SearchAPIData.dish.name[counter]){selected="cursor_"+loopVar+"_"+loop;if(search.Selections.dish.name!=""){$("#"+selected).addClass("selectedDishREst");}}}
counter++;}}
if(search.Selections.dish.name.length>0){$("#selectType").css("display","block");}else{$("#selectType").css("display","none");}}
row=0;obj.arrowCheck();obj.enter_focus();search.searchMenuContainer.checkForEmptySearch();}
obj.createGrid=function(param){try{var param=param||"";if(param.state&&param.state=="init"){global.clearContents();global.mainMenu.makeSelected(0);search.searchMenuContainer.createMenu(param.screen);global.mainMenu.leave_focus();global.focusedDom=search;}
search.freeContent();if(search.SearchAPIData.theme.id.length==0&&(search.curMenu==4)){global.showError("theme","dontClearBtm");search.searchMenuContainer.enter_focus(search.curMenu);return false;}else if(search.SearchAPIData.price.id.length==0&&(search.curMenu==5)){global.showError("price","dontClearBtm");search.searchMenuContainer.enter_focus(search.curMenu);return false;}
obj.free();obj.createPrice();$("#selectType").css("display","none");$("#numberVal").css("visibility","hidden");var grid="<div id='leftArrowCont'><div id='leftArr'></div></div><div id='gridCentre'></div><div id='rightArrowCont'><div id='rightArr'></div></div>";$("#thumbnail").append(grid);grid="";$("#rightArrowCont").css("margin-left","1356px");$("#leftArrowCont").css("margin-left","33px");if(search.curMenu==5){totalPages=parseInt(search.SearchAPIData.price.name.length/15);if(search.SearchAPIData.price.name.length%15!=0){totalPages++;}
obj.createPage();if(totalPages<=1){$("#searchPage").css("display","none");}
$("#selectMenu").text(search.select[search.curMenu]);$("#price").text("Price");if(search.SearchAPIData.price.name.length<=15){$("#rightArr").css("visibility","hidden");$("#leftArr").css("visibility","hidden");}
if(search.SearchAPIData.price.name.length<3){totalRows=search.SearchAPIData.price.name.length}else{totalRows=search.SearchAPIData.price.name.length/3;}
if(search.SearchAPIData.price.name.length%3!=0){totalRows++;}
if(totalRows>5){row=5;}else{row=parseInt(totalRows);}
for(var loopVar=0;loopVar<row;loopVar++){for(var loop=0;loop<3;loop++){if(counter==search.SearchAPIData.price.name.length){break;}
grid="<div id='grid_"+loopVar+"_"+loop+"' class='gridTheme fontstyleGridTheme'><div id='grid"+loopVar+"_"+loop+"' class='gridDivText'>"+search.SearchAPIData.price.name[counter]+"</div></div>";$("#gridCentre").append(grid);if(search.Selections.price.name==search.SearchAPIData.price.name[counter]){selected="grid_"+loopVar+"_"+loop;if(search.curMenu==5){if(search.Selections.price.name!=""){$("#"+selected).addClass("selectedGrid");previous=selected;}}}
counter++;}}
if(search.Selections.price.name.length!=""){$("#selectType").css("display","block");$("#selectedNumber").css("display","none");$("#numberVal").css("display","none");$("#clearAll").css("display","block");}}else{totalPages=parseInt(search.SearchAPIData.theme.name.length/15);if(search.SearchAPIData.theme.name.length%15!=0){totalPages++;}
obj.createPage();if(totalPages<=1){$("#searchPage").css("display","none");}
$("#selectMenu").text(search.select[search.curMenu]);$("#price").text("Themes");if(search.SearchAPIData.theme.name.length<=15){$("#rightArr").css("visibility","hidden");$("#leftArr").css("visibility","hidden");}
if(search.SearchAPIData.theme.name.length<3){totalRows=search.SearchAPIData.theme.name.length}else{totalRows=search.SearchAPIData.theme.name.length/3;}
if(search.SearchAPIData.theme.name.length%3!=0){totalRows++;}
if(totalRows>5){row=5;}else{row=parseInt(totalRows);}
for(var loopVar=0;loopVar<row;loopVar++){for(var loop=0;loop<3;loop++){if(counter==search.SearchAPIData.theme.name.length){break;}
grid='<div id="grid_'+loopVar+'_'+loop+'" class="gridTheme fontstyleGridTheme"><div id="grid'+loopVar+'_'+loop+'" class="gridDivText">'+search.SearchAPIData.theme.name[counter]+'</div></div>';$("#gridCentre").append(grid);if(search.Selections.theme.name==search.SearchAPIData.theme.name[counter]){selected="grid_"+loopVar+"_"+loop;if(search.Selections.theme.name!=""){$("#"+selected).addClass("selectedGrid");previous=selected;}}
counter++;}}
if(search.Selections.theme.name!=""){$("#selectType").css("display","block");$("#selectedNumber").css("display","none");$("#numberVal").css("display","none");$("#clearAll").css("display","block");}}
row=0;obj.arrowCheck();obj.enter_focus();search.searchMenuContainer.checkForEmptySearch();}catch(e){}};obj.createPage=function(){if($("#searchPage").length>0){$("#searchPage").remove();}
outer="<div id='searchPage'>"+page+" of "+totalPages+"</div>";$("#thumbnail").append(outer);}
obj.arrowCheck=function(){var len=0;switch(search.curMenu){case 2:len=search.SearchAPIData.dish.name.length;break;case 3:len=search.SearchAPIData.restaurantType.name.length;break;case 4:len=search.SearchAPIData.theme.name.length;break;case 5:len=search.SearchAPIData.price.name.length;break;default:break;}
if(counter<len){$("#rightArr").css("background-position","0px -40px");}else{$("#rightArr").css("background-position","0px 7px");}
if(page==1){$("#leftArr").css("background-position","0px 7px");}else{$("#leftArr").css("background-position","0px -40px");}}
obj.enter_focus=function(){global.focusedDom=this;if(this.leftRetVal=="grid"){if(search.curMenu==5||search.curMenu==4){$("#grid_"+row+"_"+column).addClass("cursorGrid");}else{$("#grid_"+row+"_"+column).addClass("cursorDishRest");}
search.row_col={"row":row,"col":column,"leftRetVal":this.leftRetVal};}else{obj.enter_focus_price();}};obj.leave_focus=function(row,column){if(search.curMenu==5||search.curMenu==4){$("#grid_"+row+"_"+column).removeClass("cursorGrid");}else{$("#grid_"+row+"_"+column).removeClass("cursorDishRest");}};obj.enter_focus_price=function(){global.focusedDom=this;this.leftRetVal="grid";$("#price").addClass("priceCursor");}
obj.leave_focus_price=function(){$("#price").removeClass("priceCursor");}
obj.createPrice=function(){menu="";menu="<div id='label'><div id='selectMenu'></div><div id='selectType'><div id='selectedNumber'>Selected:</div><div id='numberVal'></div><div class='clearAll' id='clearAll'></div></div></div><div id='priceOuter'><div id='price'></div></div><div id='thumbnail'></div>";if($("#label").length>0){$("#label").remove();}
$("#innerSection").append(menu);};obj.free=function(){$("#thumbnail").html("");row=0;column=0;$("#label").remove();$("#priceOuter").remove();$("#thumbnail").remove();};obj.freeAll=function(){obj.free();counter=0;page=1;row=0;column=0;totalRows=0;selected="";previous="";index=0;this.leftRetVal="grid";$("#label").remove();$("#priceOuter").remove();$("#thumbnail").remove();}
obj.popUpHide=function(){$("#maxLimitPopUp").fadeTo(1000,0,function(){$("#maxLimitPopUp").remove();});}
obj.popUpCreate=function(){var popUp="<div id='maxLimitPopUp' class = 'maxLimitPopUp'><div id=maxLimitInfoIcon></div>Please select at most 5 options.</div>";$('body').append(popUp);search.maxLimitTimerObj=setTimeout(function(){obj.popUpHide();},3000);};obj.clearAll=function(cur){search.menusWithSelection[cur]=false;$("#star_"+cur).css("visibility","hidden");switch(cur){case 2:search.Selections.dish.name=[];search.Selections.dish.id=[];var tot_Rows=search.SearchAPIData.dish.name.length/3;if(search.SearchAPIData.dish.name.length%3!=0){tot_Rows++;}
var rows=0;if(tot_Rows>6){rows=6;}else{rows=parseInt(tot_Rows);}
for(var loopVar=0;loopVar<rows;loopVar++){for(var loop=0;loop<3;loop++){$("#cursor_"+loopVar+"_"+loop).removeClass("selectedDishREst");}}
$("#numberVal").text("0");break;case 3:search.Selections.restaurantType.name=[];search.Selections.restaurantType.id=[];var tot_Rows=search.SearchAPIData.restaurantType.name.length/3;if(search.SearchAPIData.restaurantType.name.length%3!=0){tot_Rows++;}
var rows=0;if(tot_Rows>6){rows=6;}else{rows=parseInt(tot_Rows);}
for(var loopVar=0;loopVar<rows;loopVar++){for(var loop=0;loop<3;loop++){$("#cursor_"+loopVar+"_"+loop).removeClass("selectedDishREst");}}
$("#numberVal").text("0");break;case 4:search.Selections.theme.name="";search.Selections.theme.id="";$("#"+selected).removeClass("selectedGrid");break;case 5:search.Selections.price.name="";search.Selections.price.id="";$("#"+selected).removeClass("selectedGrid");break;}
$("#selectType").css("display","none");if(global.focusedDom===hotKeyObj){hotKeyObj.enter_focus();}else if($("#clearAll").hasClass("clearCursor")){search.searchMenuContainer.leave_focus_clear();row=0;column=0;obj.enter_focus();}}
obj.KeyboardEvent=function(e,eventType){try{var target=_target(e),keyCode=target.keyCode,key=global.keyCodeDic[keyCode];switch(eventType){case"keydown":switch(key){case"arrowdown":try{var columnTemp=column;var rowTemp;if($("#price").hasClass('priceCursor')){obj.enter_focus();obj.leave_focus_price();}else{if(search.curMenu==5){rowTemp=search.SearchAPIData.price.name.length/3;if(search.SearchAPIData.price.name.length%3!=0){rowTemp++;}}else{switch(search.curMenu){case 4:len=search.SearchAPIData.theme.name.length;break;case 3:len=search.SearchAPIData.restaurantType.name.length;break;case 2:len=search.SearchAPIData.dish.name.length;break;}
rowTemp=len/3;if(len%3!=0){rowTemp++;}}
row++;if($("#grid_"+row+"_"+column).length){obj.leave_focus(row-1,column);obj.enter_focus(row,column);}else{while(column>0){column--;if($("#grid_"+row+"_"+column).length){obj.leave_focus(row-1,columnTemp);obj.enter_focus(row,column);return true;}}
column=columnTemp;row--;obj.leave_focus(row,column);hotKeyObj.enter_focus();return false;}}}catch(e){}
break;case"arrowup":try{row--;if(row>=0){obj.leave_focus(row+1,column);obj.enter_focus(row,column);}else{row++
obj.leave_focus(row,column);if($("#price").hasClass("priceCursor")){obj.leave_focus_price();if($("#selectType").css("display")=="block"){search.searchMenuContainer.enter_focus_clear();}else{search.searchMenuContainer.enter_focus(search.curMenu);}}else{obj.enter_focus_price();}
return true;}}catch(e){}
return true;break;case"ok":if(!$("#price").hasClass("priceCursor")){switch(search.curMenu){case 5:selected="grid_"+row+"_"+column;$("#selectedNumber").css("display","none");$("#numberVal").css("display","none");if($("#"+selected).hasClass("selectedGrid")){search.Selections.price.name="";search.Selections.price.id="";$("#selectType").css("display","none");$("#star_"+search.curMenu).css("visibility","hidden");search.menusWithSelection[search.curMenu]=false;}else{search.Selections.price.name=$("#"+selected).text();search.Selections.price.id=search.SearchAPIData.price.id[(page-1)*15+(row*3+column)];$("#selectType").css("display","block");$("#star_"+search.curMenu).css("visibility","visible");search.menusWithSelection[search.curMenu]=true;if(previous!=""){$("#"+previous).removeClass("selectedGrid");}
previous="grid_"+row+"_"+column;}
$("#"+selected).toggleClass("selectedGrid");break;case 4:selected="grid_"+row+"_"+column;$("#selectedNumber").css("display","none");$("#numberVal").css("display","none");if($("#"+selected).hasClass("selectedGrid")){search.Selections.theme.name="";search.Selections.theme.id="";$("#selectType").css("display","none");$("#star_"+search.curMenu).css("visibility","hidden");search.menusWithSelection[search.curMenu]=false;}else{search.Selections.theme.name=$("#"+selected).text();search.Selections.theme.id=search.SearchAPIData.theme.id[(page-1)*15+(row*3+column)];$("#selectType").css("display","block");$("#star_"+search.curMenu).css("visibility","visible");search.menusWithSelection[search.curMenu]=true;if(previous!=""){$("#"+previous).removeClass("selectedGrid");}
previous="grid_"+row+"_"+column;}
$("#"+selected).toggleClass("selectedGrid");break;case 3:selected="cursor_"+row+"_"+column;if($("#"+selected).hasClass("selectedDishREst")){index=search.Selections.restaurantType.name.indexOf($("#"+selected).text());search.Selections.restaurantType.name.splice(index,1);search.Selections.restaurantType.id.splice(index,1);if(search.Selections.restaurantType.id.length==0){search.menusWithSelection[search.curMenu]=false;$("#star_"+search.curMenu).css("visibility","hidden");$("#selectType").css("display","none");}}else{if(search.Selections.restaurantType.id.length>4){if($("#maxLimitPopUp").length==0){obj.popUpCreate();}
break;}
search.Selections.restaurantType.name.push($("#"+selected).text());search.Selections.restaurantType.id.push(search.SearchAPIData.restaurantType.id[(page-1)*18+(row*3+column)]);search.menusWithSelection[search.curMenu]=true;$("#star_"+search.curMenu).css("visibility","visible");$("#selectType").css("display","block");}
$("#numberVal").text(search.Selections.restaurantType.id.length);$("#"+selected).toggleClass("selectedDishREst");break;case 2:selected="cursor_"+row+"_"+column;if($("#"+selected).hasClass("selectedDishREst")){index=search.Selections.dish.name.indexOf($("#"+selected).text());search.Selections.dish.name.splice(index,1);search.Selections.dish.id.splice(index,1);if(search.Selections.dish.id.length==0){search.menusWithSelection[search.curMenu]=false;$("#star_"+search.curMenu).css("visibility","hidden");$("#selectType").css("display","none");}}else{if(search.Selections.dish.id.length>4){if($("#maxLimitPopUp").length==0){obj.popUpCreate();}
break;}
search.Selections.dish.name.push($("#"+selected).text());search.Selections.dish.id.push(search.SearchAPIData.dish.id[(page-1)*18+(row*3+column)]);search.menusWithSelection[search.curMenu]=true;$("#star_"+search.curMenu).css("visibility","visible");$("#selectType").css("display","block");}
$("#numberVal").text(search.Selections.dish.id.length);$("#"+selected).toggleClass("selectedDishREst");break;}
search.searchMenuContainer.checkForEmptySearch();}
break;case"arrowright":try{if(!$("#price").hasClass("priceCursor")){var len=0;column++;if($("#grid_"+row+"_"+column).length){obj.leave_focus(row,column-1);obj.enter_focus(row,column);}else{switch(search.curMenu){case 5:len=search.SearchAPIData.price.name.length;break;case 4:len=search.SearchAPIData.theme.name.length;break;case 3:len=search.SearchAPIData.restaurantType.name.length;break;case 2:len=search.SearchAPIData.dish.name.length;break;}
if(search.curMenu==5||search.curMenu==4){if(counter<len){page++;obj.createGrid();column=0;}else{column--;return false;}}else{if(counter<len){page++;obj.createGrid_dishRestaurant();column=0;}else{column--;return false;}}}}}catch(e){}
return true;break;case"arrowleft":try{if(!$("#price").hasClass("priceCursor")){column--;if($("#grid_"+row+"_"+column).length){obj.leave_focus(row,column+1);obj.enter_focus(row,column);}else{if(page!=1){counter-=$("#gridCentre").children().length;page--;if(search.curMenu==5||search.curMenu==4){counter-=15;obj.createGrid();}else{counter-=18;obj.createGrid_dishRestaurant();}
column=0;}else{column++;obj.leave_focus(row,column);this.leftRetVal="grid";column=0;global.mainMenu.enter_focus();return true;}}}else{this.leftRetVal="price";obj.leave_focus_price();global.mainMenu.enter_focus();}}catch(e){}
return true;break;}
return false;}
return false;}catch(e){}};return obj;})();search.searchMenuContainer=(function(){var obj={};search.curFocusMenu=0;obj.createMenu=function(selMenu){var selMenu=selMenu||0;global.clearContents();search.curFocusMenu=selMenu;search.curMenu=selMenu;var menu="<div id='menuCont'></div>";$("#innerSection").append(menu);menu="";for(var loopVar=0;loopVar<6;loopVar++){menu+="<div  id='menu_"+loopVar+"' class='menuOption fontStyle' select='0'>"+search.menu[loopVar]+"<div  class='selectedIndication' id='star_"+loopVar+"'></div></div>";}
$("#menuCont").append(menu);$("#menu_"+search.curFocusMenu).addClass("selectedMenu");$("#menu_"+search.curFocusMenu).attr("select","1");obj.setStar();global.createHotKey();};obj.setStar=function(){for(var i=0;i<search.menusWithSelection.length;i++){if(search.menusWithSelection[i]){$("#star_"+i).css("visibility","visible");}}}
obj.enter_focus=function(index){global.focusedDom=this;if($("#menu_"+index).attr('select')=="1"){search.curFocusMenu=search.curMenu;$("#menu_"+index).removeClass("selectedMenu");$("#menu_"+index).addClass("topMenuSelectedCursor");}else{$("#menu_"+index).addClass("topMenuCursor");}};obj.enter_focus_clear=function(){global.focusedDom=this;$("#clearAll").addClass("clearCursor");}
obj.leave_focus_clear=function(){$("#clearAll").removeClass("clearCursor");}
obj.leave_focus=function(index){$("#menu_"+index).removeClass("topMenuCursor");if($("#menu_"+index).attr('select')=="1"){$("#menu_"+index).removeClass("topMenuSelectedCursor");$("#menu_"+index).addClass("selectedMenu");}};obj.clear=function(){$("#innerSection").html("");$("#bottomSection").removeClass("bottomSectionBg");$("#bottomSection").html("");}
obj.menuEnter=function(direction){hotKeyObj.hotKeyCur=1;global.mainMenu.leave_focus();$("#menu_"+search.curMenu).removeClass("selectedMenu");$("#menu_"+search.curMenu).removeClass("topMenuSelectedCursor");$("#menu_"+search.curMenu).attr("select","0");obj.leave_focus(search.curFocusMenu);if(direction=="right"){if(search.curMenu==5){search.curFocusMenu=0;}else{search.curFocusMenu=parseInt(search.curMenu)+1;}}else{if(search.curMenu==0){search.curFocusMenu=5;}else{search.curFocusMenu=parseInt(search.curMenu)-1;}}
search.curMenu=search.curFocusMenu;$("#menu_"+search.curFocusMenu).attr("select","1");$("#menu_"+search.curFocusMenu).addClass("selectedMenu");search.menuGridContainer.freeAll();search.showSearchScreen({"screen":search.curMenu,"state":""});}
obj.checkForEmptySearch=function(){for(var loop=0;loop<6;loop++){if($("#star_"+loop).css("visibility")=="hidden"){$("#label_3").css("color","#c4aa97");$("#yellowhotKeyImg").css("opacity","0.4");}else{$("#label_3").css("color","white");$("#yellowhotKeyImg").css("opacity","1");break;}}}
obj.KeyboardEvent=function(e,eventType){try{var target=_target(e),keyCode=target.keyCode,key=global.keyCodeDic[keyCode];switch(eventType){case"keydown":switch(key){case"arrowdown":if(($("#content").length>0)||($("#thumbnail").length>0)&&(region.accordionScreen!="location")){if(search.curMenu==0||search.curMenu==1){obj.leave_focus(search.curFocusMenu);if(($("#acc_clear").css("display"))=="block"){region.clear.enter_focus();}else{region.set_focus();}}else{if($("#selectType").css("display")=="block"){if($("#clearAll").hasClass('clearCursor')){obj.leave_focus_clear();search.menuGridContainer.enter_focus_price();}else{obj.leave_focus(search.curFocusMenu);search.curFocusMenu=search.curMenu;obj.enter_focus_clear();}}else{obj.leave_focus(search.curFocusMenu);search.curFocusMenu=search.curMenu;search.menuGridContainer.enter_focus_price();}}}else{obj.leave_focus(search.curFocusMenu);hotKeyObj.enter_focus();}
return false;break;case"ok":if($("#clearAll").length>0&&$("#clearAll").hasClass('clearCursor')){search.menuGridContainer.clearAll(search.curMenu);obj.checkForEmptySearch();$("#selectType").css("display","none");}else if(search.curMenu!=search.curFocusMenu){hotKeyObj.hotKeyCur=1;$("#menu_"+search.curMenu).removeClass("selectedMenu");$("#menu_"+search.curMenu).attr("select","0");search.curMenu=search.curFocusMenu;$("#menu_"+search.curFocusMenu).attr("select","1");$("#menu_"+search.curFocusMenu).addClass("selectedMenu");obj.leave_focus(search.curFocusMenu);search.menuGridContainer.freeAll();search.showSearchScreen({"screen":search.curMenu,"state":""})}
break;case"arrowright":if(!$("#clearAll").hasClass('clearCursor')){if($("#menu_"+(search.curFocusMenu+1)).length){obj.leave_focus(search.curFocusMenu);search.curFocusMenu++;obj.enter_focus(search.curFocusMenu);}}
break;case"arrowleft":if(!$("#clearAll").hasClass('clearCursor')){if($("#menu_"+(search.curFocusMenu-1)).length){obj.leave_focus(search.curFocusMenu);search.curFocusMenu--;obj.enter_focus(search.curFocusMenu);}else{obj.leave_focus(search.curFocusMenu);search.menuGridContainer.leftRetVal="price";global.mainMenu.enter_focus();}}
return true;break;case"arrowup":if($("#selectType").css("display")=="block"&&$("#clearAll").hasClass('clearCursor')){obj.leave_focus_clear();obj.enter_focus(search.curMenu);}
break;}
return false;}
return false;}catch(e){}};return obj;})();